package beans;
// Generated Jul 29, 2009 10:15:00 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * TblCxcMovimientos generated by hbm2java
 */
public class TblCxcMovimientos  implements java.io.Serializable {


     private TblCxcMovimientosId id;
     private String idEjercicioFiscal;
     private int idMes;
     private Date fecha;
     private BigDecimal monto;
     private String idMoneda;
     private BigDecimal tasaCambio;
     private BigDecimal montoLocal;
     private Integer idOrdenCompra;
     private Date fechaVence;
     private int diasCredito;
     private String idCuentaContable;
     private String descripcion;
     private Integer autorizado;
     private String contrasenia;

     private Double saldo;
     private int diasVencida;

    public TblCxcMovimientos() {
    }

	
    public TblCxcMovimientos(TblCxcMovimientosId id, String idEjercicioFiscal, int idMes, Date fecha, BigDecimal monto, String idMoneda, BigDecimal tasaCambio, BigDecimal montoLocal, Date fechaVence, int diasCredito, String idCuentaContable, String contrasenia) {
        this.id = id;
        this.idEjercicioFiscal = idEjercicioFiscal;
        this.idMes = idMes;
        this.fecha = fecha;
        this.monto = monto;
        this.idMoneda = idMoneda;
        this.tasaCambio = tasaCambio;
        this.montoLocal = montoLocal;
        this.fechaVence = fechaVence;
        this.diasCredito = diasCredito;
        this.idCuentaContable = idCuentaContable;
        this.contrasenia = contrasenia;
    }
    public TblCxcMovimientos(TblCxcMovimientosId id, String idEjercicioFiscal, int idMes, Date fecha, BigDecimal monto, String idMoneda, BigDecimal tasaCambio, BigDecimal montoLocal, Integer idOrdenCompra, Date fechaVence, int diasCredito, String idCuentaContable, String descripcion, Integer autorizado, String contrasenia) {
       this.id = id;
       this.idEjercicioFiscal = idEjercicioFiscal;
       this.idMes = idMes;
       this.fecha = fecha;
       this.monto = monto;
       this.idMoneda = idMoneda;
       this.tasaCambio = tasaCambio;
       this.montoLocal = montoLocal;
       this.idOrdenCompra = idOrdenCompra;
       this.fechaVence = fechaVence;
       this.diasCredito = diasCredito;
       this.idCuentaContable = idCuentaContable;
       this.descripcion = descripcion;
       this.autorizado = autorizado;
       this.contrasenia = contrasenia;
    }
   
    public TblCxcMovimientosId getId() {
        return this.id;
    }
    
    public void setId(TblCxcMovimientosId id) {
        this.id = id;
    }
    public String getIdEjercicioFiscal() {
        return this.idEjercicioFiscal;
    }
    
    public void setIdEjercicioFiscal(String idEjercicioFiscal) {
        this.idEjercicioFiscal = idEjercicioFiscal;
    }
    public int getIdMes() {
        return this.idMes;
    }
    
    public void setIdMes(int idMes) {
        this.idMes = idMes;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public String getIdMoneda() {
        return this.idMoneda;
    }
    
    public void setIdMoneda(String idMoneda) {
        this.idMoneda = idMoneda;
    }
    public BigDecimal getTasaCambio() {
        return this.tasaCambio;
    }
    
    public void setTasaCambio(BigDecimal tasaCambio) {
        this.tasaCambio = tasaCambio;
    }
    public BigDecimal getMontoLocal() {
        return this.montoLocal;
    }
    
    public void setMontoLocal(BigDecimal montoLocal) {
        this.montoLocal = montoLocal;
    }
    public Integer getIdOrdenCompra() {
        return this.idOrdenCompra;
    }
    
    public void setIdOrdenCompra(Integer idOrdenCompra) {
        this.idOrdenCompra = idOrdenCompra;
    }
    public Date getFechaVence() {
        return this.fechaVence;
    }
    
    public void setFechaVence(Date fechaVence) {
        this.fechaVence = fechaVence;
    }
    public int getDiasCredito() {
        return this.diasCredito;
    }
    
    public void setDiasCredito(int diasCredito) {
        this.diasCredito = diasCredito;
    }
    public String getIdCuentaContable() {
        return this.idCuentaContable;
    }
    
    public void setIdCuentaContable(String idCuentaContable) {
        this.idCuentaContable = idCuentaContable;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getAutorizado() {
        return this.autorizado;
    }
    
    public void setAutorizado(Integer autorizado) {
        this.autorizado = autorizado;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

    public Double getSaldo() {
        return saldo;
    }

    public void setSaldo(Double saldo) {
        this.saldo = saldo;
    }

    public int getDiasVencida() {
        return diasVencida;
    }

    public void setDiasVencida(int diasVencida) {
        this.diasVencida = diasVencida;
    }
}


