package beans;
// Generated Aug 27, 2009 4:33:32 PM by Hibernate Tools 3.2.1.GA



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int id;
     private String username;
     private String password;
     private String name;
     private String lastname;
     private String email;
     private String email1;
     private String tel;
     private String cel;
     private String address;
     private int locationId;
     private Boolean customerAgent;
     private Boolean salesRepresentative;
     private String rowguid;

    public Users() {
    }

	
    public Users(int id, String username, String name, String lastname, int locationId, String rowguid) {
        this.id = id;
        this.username = username;
        this.name = name;
        this.lastname = lastname;
        this.locationId = locationId;
        this.rowguid = rowguid;
    }
    public Users(int id, String username, String password, String name, String lastname, String email, String email1, String tel, String cel, String address, int locationId, Boolean customerAgent, Boolean salesRepresentative, String rowguid) {
       this.id = id;
       this.username = username;
       this.password = password;
       this.name = name;
       this.lastname = lastname;
       this.email = email;
       this.email1 = email1;
       this.tel = tel;
       this.cel = cel;
       this.address = address;
       this.locationId = locationId;
       this.customerAgent = customerAgent;
       this.salesRepresentative = salesRepresentative;
       this.rowguid = rowguid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmail1() {
        return email1;
    }

    public void setEmail1(String email1) {
        this.email1 = email1;
    }
    
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getCel() {
        return this.cel;
    }
    
    public void setCel(String cel) {
        this.cel = cel;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public int getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(int locationId) {
        this.locationId = locationId;
    }
    public Boolean getCustomerAgent() {
        return this.customerAgent;
    }
    
    public void setCustomerAgent(Boolean customerAgent) {
        this.customerAgent = customerAgent;
    }
    public Boolean getSalesRepresentative() {
        return this.salesRepresentative;
    }
    
    public void setSalesRepresentative(Boolean salesRepresentative) {
        this.salesRepresentative = salesRepresentative;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }




}


