package beans;
// Generated Jul 24, 2009 2:23:28 PM by Hibernate Tools 3.2.1.GA



/**
 * Currencies generated by hbm2java
 */
public class Currencies  implements java.io.Serializable {


     private int id;
     private String name;
     private String symbol;
     private String code;
     private String exchangeRate;
     private String rowguid;

    public Currencies() {
    }

	
    public Currencies(int id, String rowguid) {
        this.id = id;
        this.rowguid = rowguid;
    }
    public Currencies(int id, String name, String symbol, String code, String exchangeRate, String rowguid) {
       this.id = id;
       this.name = name;
       this.symbol = symbol;
       this.code = code;
       this.exchangeRate = exchangeRate;
       this.rowguid = rowguid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSymbol() {
        return this.symbol;
    }
    
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getExchangeRate() {
        return this.exchangeRate;
    }
    
    public void setExchangeRate(String exchangeRate) {
        this.exchangeRate = exchangeRate;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }




}


