package beans;
// Generated May 21, 2009 3:23:26 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;

/**
 * Warehouses generated by hbm2java
 */
public class Warehouses  implements java.io.Serializable {


     private int id;
     private Integer customerId;
     private Integer shipperId;
     private String destinationId;
     private Date initDate;
     private String proNumber;
     private Integer inlandCarrierId;
     private Integer statusId;
     private Integer locationRackId;
     private String routingId;
     private String orderNo;
     private String refNo;
     private BigDecimal mercValue;
     private Boolean originalInvoice;
     private Boolean packingList;
     private String description;
     private String marks;
     private Boolean divided;
     private Boolean active;
     private int locationId;
     private String statusImage;
     private String stepId;
     private Integer customerDestinationId;
     private Integer locationServiceId;
     private Integer destinationLocationId;
     private Date routingDate;
     private Boolean dangerousGoods;
     private String locationRackComment;
     private String rowguid;
     private Integer routingLocation;
     private String routingUser;
     private String currency;

     private Customers customer;
     private Shippers shipper;
     private Carriers inlandCarrier;
     private LocationRacks locationRack;
     private Status status;
     private String origenCity;
     private Integer pieces;
     private Double weight;
     private Double volWeight;
     private Double cft;
     private ArrayList<WarehouseDetails> warehouseDetail;

    public Warehouses() {
    }

	
    public Warehouses(int id, int locationId, String rowguid) {
        this.id = id;
        this.locationId = locationId;
        this.rowguid = rowguid;
    }
    public Warehouses(int id, Integer customerId, Integer shipperId, String destinationId, Date initDate, String proNumber, Integer inlandCarrierId, Integer statusId, Integer locationRackId, String routingId, String orderNo, String refNo, BigDecimal mercValue, Boolean originalInvoice, Boolean packingList, String description, String marks, Boolean divided, Boolean active, int locationId, String statusImage, String stepId, Integer customerDestinationId, Integer locationServiceId, Integer destinationLocationId, Date routingDate, Boolean dangerousGoods, String locationRackComment, String rowguid, Integer routingLocation, String routingUser, String currency) {
       this.id = id;
       this.customerId = customerId;
       this.shipperId = shipperId;
       this.destinationId = destinationId;
       this.initDate = initDate;
       this.proNumber = proNumber;
       this.inlandCarrierId = inlandCarrierId;
       this.statusId = statusId;
       this.locationRackId = locationRackId;
       this.routingId = routingId;
       this.orderNo = orderNo;
       this.refNo = refNo;
       this.mercValue = mercValue;
       this.originalInvoice = originalInvoice;
       this.packingList = packingList;
       this.description = description;
       this.marks = marks;
       this.divided = divided;
       this.active = active;
       this.locationId = locationId;
       this.statusImage = statusImage;
       this.stepId = stepId;
       this.customerDestinationId = customerDestinationId;
       this.locationServiceId = locationServiceId;
       this.destinationLocationId = destinationLocationId;
       this.routingDate = routingDate;
       this.dangerousGoods = dangerousGoods;
       this.locationRackComment = locationRackComment;
       this.rowguid = rowguid;
       this.routingLocation = routingLocation;
       this.routingUser = routingUser;
       this.currency = currency;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    public Integer getShipperId() {
        return this.shipperId;
    }
    
    public void setShipperId(Integer shipperId) {
        this.shipperId = shipperId;
    }
    public String getDestinationId() {
        return this.destinationId;
    }
    
    public void setDestinationId(String destinationId) {
        this.destinationId = destinationId;
    }
    public Date getInitDate() {
        return this.initDate;
    }
    
    public void setInitDate(Date initDate) {
        this.initDate = initDate;
    }
    public String getProNumber() {
        return this.proNumber;
    }
    
    public void setProNumber(String proNumber) {
        this.proNumber = proNumber;
    }
    public Integer getInlandCarrierId() {
        return this.inlandCarrierId;
    }
    
    public void setInlandCarrierId(Integer inlandCarrierId) {
        this.inlandCarrierId = inlandCarrierId;
    }
    public Integer getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }
    public Integer getLocationRackId() {
        return this.locationRackId;
    }
    
    public void setLocationRackId(Integer locationRackId) {
        this.locationRackId = locationRackId;
    }
    public String getRoutingId() {
        return this.routingId;
    }
    
    public void setRoutingId(String routingId) {
        this.routingId = routingId;
    }
    public String getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }
    public String getRefNo() {
        return this.refNo;
    }
    
    public void setRefNo(String refNo) {
        this.refNo = refNo;
    }
    public BigDecimal getMercValue() {
        return this.mercValue;
    }
    
    public void setMercValue(BigDecimal mercValue) {
        this.mercValue = mercValue;
    }
    public Boolean getOriginalInvoice() {
        return this.originalInvoice;
    }
    
    public void setOriginalInvoice(Boolean originalInvoice) {
        this.originalInvoice = originalInvoice;
    }
    public Boolean getPackingList() {
        return this.packingList;
    }
    
    public void setPackingList(Boolean packingList) {
        this.packingList = packingList;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getMarks() {
        return this.marks;
    }
    
    public void setMarks(String marks) {
        this.marks = marks;
    }
    public Boolean getDivided() {
        return this.divided;
    }
    
    public void setDivided(Boolean divided) {
        this.divided = divided;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public int getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(int locationId) {
        this.locationId = locationId;
    }
    public String getStatusImage() {
        return this.statusImage;
    }
    
    public void setStatusImage(String statusImage) {
        this.statusImage = statusImage;
    }
    public String getStepId() {
        return this.stepId;
    }
    
    public void setStepId(String stepId) {
        this.stepId = stepId;
    }
    public Integer getCustomerDestinationId() {
        return this.customerDestinationId;
    }
    
    public void setCustomerDestinationId(Integer customerDestinationId) {
        this.customerDestinationId = customerDestinationId;
    }
    public Integer getLocationServiceId() {
        return this.locationServiceId;
    }
    
    public void setLocationServiceId(Integer locationServiceId) {
        this.locationServiceId = locationServiceId;
    }
    public Integer getDestinationLocationId() {
        return this.destinationLocationId;
    }
    
    public void setDestinationLocationId(Integer destinationLocationId) {
        this.destinationLocationId = destinationLocationId;
    }
    public Date getRoutingDate() {
        return this.routingDate;
    }
    
    public void setRoutingDate(Date routingDate) {
        this.routingDate = routingDate;
    }
    public Boolean getDangerousGoods() {
        return this.dangerousGoods;
    }
    
    public void setDangerousGoods(Boolean dangerousGoods) {
        this.dangerousGoods = dangerousGoods;
    }
    public String getLocationRackComment() {
        return this.locationRackComment;
    }
    
    public void setLocationRackComment(String locationRackComment) {
        this.locationRackComment = locationRackComment;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }
    public Integer getRoutingLocation() {
        return this.routingLocation;
    }
    
    public void setRoutingLocation(Integer routingLocation) {
        this.routingLocation = routingLocation;
    }
    public String getRoutingUser() {
        return this.routingUser;
    }
    
    public void setRoutingUser(String routingUser) {
        this.routingUser = routingUser;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public Customers getCustomer() {
        return customer;
    }

    public void setCustomer(Customers customer) {
        this.customer = customer;
    }

    public Shippers getShipper() {
        return shipper;
    }

    public void setShipper(Shippers shipper) {
        this.shipper = shipper;
    }

    public Carriers getInlandCarrier() {
        return inlandCarrier;
    }

    public void setInlandCarrier(Carriers inlandCarrier) {
        this.inlandCarrier = inlandCarrier;
    }

    public LocationRacks getLocationRack() {
        return locationRack;
    }

    public void setLocationRack(LocationRacks locationRack) {
        this.locationRack = locationRack;
    }

    public String getOrigenCity() {
        return origenCity;
    }

    public void setOrigenCity(String origenCity) {
        this.origenCity = origenCity;
    }

    public Integer getPieces() {
        return pieces;
    }

    public void setPieces(Integer pieces) {
        this.pieces = pieces;
    }

    public Double getWeight() {
        return weight;
    }

    public void setWeight(Double weight) {
        this.weight = weight;
    }

    public Double getCft() {
        return cft;
    }

    public void setCft(Double cft) {
        this.cft = cft;
    }

    public Double getVolWeight() {
        return volWeight;
    }

    public void setVolWeight(Double volWeight) {
        this.volWeight = volWeight;
    }

    public ArrayList<WarehouseDetails> getWarehouseDetail() {
        return warehouseDetail;
    }

    public void setWarehouseDetail(ArrayList<WarehouseDetails> warehouseDetail) {
        this.warehouseDetail = warehouseDetail;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }
}