package beans;
// Generated Aug 5, 2009 11:55:38 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * WebUserMessages generated by hbm2java
 */
public class WebUserMessages  implements java.io.Serializable {


     private int id;
     private String action;
     private String message;
     private Date initDate;
     private Integer customerId;

    public WebUserMessages() {
    }

	
    public WebUserMessages(int id) {
        this.id = id;
    }
    public WebUserMessages(int id, String action, String message, Date initDate, Integer customerId) {
       this.id = id;
       this.action = action;
       this.message = message;
       this.initDate = initDate;
       this.customerId = customerId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Date getInitDate() {
        return this.initDate;
    }
    
    public void setInitDate(Date initDate) {
        this.initDate = initDate;
    }
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }




}


