package beans;
// Generated May 21, 2009 3:23:26 PM by Hibernate Tools 3.2.1.GA



/**
 * WebUsers generated by hbm2java
 */
public class WebUsers  implements java.io.Serializable {


     private int id;
     private String username;
     private String password;
     private String email;
     private Integer customerId;
     private Boolean active;
     private String country;

    public WebUsers() {
    }

	
    public WebUsers(int id) {
        this.id = id;
    }
    public WebUsers(int id, String username, String password, String email, Integer customerId, Boolean active, String country) {
       this.id = id;
       this.username = username;
       this.password = password;
       this.email = email;
       this.customerId = customerId;
       this.active = active;
       this.country = country;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }

    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }




}


