package beans;
// Generated 16/05/2010 09:58:09 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TrackingId generated by hbm2java
 */
@Embeddable
public class TrackingId  implements java.io.Serializable {


     private int id;
     private Date trackingDate;
     private Integer warehouseId;
     private String stepId;
     private String message;
     private String rowguid;

    public TrackingId() {
    }

	
    public TrackingId(int id, String rowguid) {
        this.id = id;
        this.rowguid = rowguid;
    }
    public TrackingId(int id, Date trackingDate, Integer warehouseId, String stepId, String message, String rowguid) {
       this.id = id;
       this.trackingDate = trackingDate;
       this.warehouseId = warehouseId;
       this.stepId = stepId;
       this.message = message;
       this.rowguid = rowguid;
    }
   

    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Column(name="trackingDate", length=23)
    public Date getTrackingDate() {
        return this.trackingDate;
    }
    
    public void setTrackingDate(Date trackingDate) {
        this.trackingDate = trackingDate;
    }

    @Column(name="warehouseId")
    public Integer getWarehouseId() {
        return this.warehouseId;
    }
    
    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }

    @Column(name="stepId", length=3)
    public String getStepId() {
        return this.stepId;
    }
    
    public void setStepId(String stepId) {
        this.stepId = stepId;
    }

    @Column(name="message", length=500)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    @Column(name="rowguid", unique=true, nullable=false, length=36)
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TrackingId) ) return false;
		 TrackingId castOther = ( TrackingId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getTrackingDate()==castOther.getTrackingDate()) || ( this.getTrackingDate()!=null && castOther.getTrackingDate()!=null && this.getTrackingDate().equals(castOther.getTrackingDate()) ) )
 && ( (this.getWarehouseId()==castOther.getWarehouseId()) || ( this.getWarehouseId()!=null && castOther.getWarehouseId()!=null && this.getWarehouseId().equals(castOther.getWarehouseId()) ) )
 && ( (this.getStepId()==castOther.getStepId()) || ( this.getStepId()!=null && castOther.getStepId()!=null && this.getStepId().equals(castOther.getStepId()) ) )
 && ( (this.getMessage()==castOther.getMessage()) || ( this.getMessage()!=null && castOther.getMessage()!=null && this.getMessage().equals(castOther.getMessage()) ) )
 && ( (this.getRowguid()==castOther.getRowguid()) || ( this.getRowguid()!=null && castOther.getRowguid()!=null && this.getRowguid().equals(castOther.getRowguid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getTrackingDate() == null ? 0 : this.getTrackingDate().hashCode() );
         result = 37 * result + ( getWarehouseId() == null ? 0 : this.getWarehouseId().hashCode() );
         result = 37 * result + ( getStepId() == null ? 0 : this.getStepId().hashCode() );
         result = 37 * result + ( getMessage() == null ? 0 : this.getMessage().hashCode() );
         result = 37 * result + ( getRowguid() == null ? 0 : this.getRowguid().hashCode() );
         return result;
   }   


}


