package beans;
// Generated Jul 21, 2009 2:25:20 PM by Hibernate Tools 3.2.1.GA



/**
 * Carriers generated by hbm2java
 */
public class Carriers  implements java.io.Serializable {


     private int id;
     private int carrierTypeId;
     private String name;
     private String phone;
     private String fax;
     private String email;
     private String accountNumber;
     private String firstName;
     private String lastName;
     private int stateId;
     private String address;
     private Integer locationId;
     private String rowguid;

    public Carriers() {
    }

	
    public Carriers(int id, int carrierTypeId, int stateId, String rowguid) {
        this.id = id;
        this.carrierTypeId = carrierTypeId;
        this.stateId = stateId;
        this.rowguid = rowguid;
    }
    public Carriers(int id, int carrierTypeId, String name, String phone, String fax, String email, String accountNumber, String firstName, String lastName, int stateId, String address, Integer locationId, String rowguid) {
       this.id = id;
       this.carrierTypeId = carrierTypeId;
       this.name = name;
       this.phone = phone;
       this.fax = fax;
       this.email = email;
       this.accountNumber = accountNumber;
       this.firstName = firstName;
       this.lastName = lastName;
       this.stateId = stateId;
       this.address = address;
       this.locationId = locationId;
       this.rowguid = rowguid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getCarrierTypeId() {
        return this.carrierTypeId;
    }
    
    public void setCarrierTypeId(int carrierTypeId) {
        this.carrierTypeId = carrierTypeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAccountNumber() {
        return this.accountNumber;
    }
    
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public int getStateId() {
        return this.stateId;
    }
    
    public void setStateId(int stateId) {
        this.stateId = stateId;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Integer getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }




}


