package beans;
// Generated Jul 28, 2009 3:14:14 PM by Hibernate Tools 3.2.1.GA



/**
 * CustomerContacts generated by hbm2java
 */
public class CustomerContacts  implements java.io.Serializable {


     private int id;
     private int customerDestinationId;
     private int prefixId;
     private String jobTitle;
     private String name;
     private String lastname;
     private String tel;
     private String cel;
     private String fax;
     private String email;
     private String address;
     private int contactClasificationId;
     private boolean availableReception;
     private Boolean infoContact;
     private Boolean accountingContact;

    public CustomerContacts() {
    }

	
    public CustomerContacts(int id, int customerDestinationId, int prefixId, String name, String lastname, int contactClasificationId, boolean availableReception) {
        this.id = id;
        this.customerDestinationId = customerDestinationId;
        this.prefixId = prefixId;
        this.name = name;
        this.lastname = lastname;
        this.contactClasificationId = contactClasificationId;
        this.availableReception = availableReception;
    }
    public CustomerContacts(int id, int customerDestinationId, int prefixId, String jobTitle, String name, String lastname, String tel, String cel, String fax, String email, String address, int contactClasificationId, boolean availableReception, Boolean infoContact, Boolean accountingContact) {
       this.id = id;
       this.customerDestinationId = customerDestinationId;
       this.prefixId = prefixId;
       this.jobTitle = jobTitle;
       this.name = name;
       this.lastname = lastname;
       this.tel = tel;
       this.cel = cel;
       this.fax = fax;
       this.email = email;
       this.address = address;
       this.contactClasificationId = contactClasificationId;
       this.availableReception = availableReception;
       this.infoContact = infoContact;
       this.accountingContact = accountingContact;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getCustomerDestinationId() {
        return this.customerDestinationId;
    }
    
    public void setCustomerDestinationId(int customerDestinationId) {
        this.customerDestinationId = customerDestinationId;
    }
    public int getPrefixId() {
        return this.prefixId;
    }
    
    public void setPrefixId(int prefixId) {
        this.prefixId = prefixId;
    }
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getCel() {
        return this.cel;
    }
    
    public void setCel(String cel) {
        this.cel = cel;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public int getContactClasificationId() {
        return this.contactClasificationId;
    }
    
    public void setContactClasificationId(int contactClasificationId) {
        this.contactClasificationId = contactClasificationId;
    }
    public boolean isAvailableReception() {
        return this.availableReception;
    }
    
    public void setAvailableReception(boolean availableReception) {
        this.availableReception = availableReception;
    }
    public Boolean getInfoContact() {
        return this.infoContact;
    }
    
    public void setInfoContact(Boolean infoContact) {
        this.infoContact = infoContact;
    }
    public Boolean getAccountingContact() {
        return this.accountingContact;
    }
    
    public void setAccountingContact(Boolean accountingContact) {
        this.accountingContact = accountingContact;
    }
}