package beans;
// Generated 16/05/2010 09:58:09 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CustomersId generated by hbm2java
 */
@Embeddable
public class CustomersId  implements java.io.Serializable {


     private int id;
     private String name;
     private String lastname;
     private boolean active;
     private boolean debt;
     private int creditDays;
     private BigDecimal creditLimit;
     private Date initDate;
     private Boolean incomplete;
     private String code;
     private Boolean retentionAgent;
     private BigDecimal taxRetained;
     private Date retentionAgentSince;
     private String tag;
     private Integer baseLocation;
     private Integer correlative;
     private String country;
     private Boolean holdCustomsClearance;
     private String invoicingComment;
     private String rowguid;
     private Date sop;
     private Integer destinationCost;
     private Boolean isCpsagent;
     private Boolean airStorage;
     private Boolean oceanStorage;
     private Integer inlandPercentage;
     private Boolean appliesTlc;
     private String countriesList;
     private Integer originCost;

    public CustomersId() {
    }

	
    public CustomersId(int id, String name, String lastname, boolean active, boolean debt, int creditDays, BigDecimal creditLimit, Date initDate, String rowguid) {
        this.id = id;
        this.name = name;
        this.lastname = lastname;
        this.active = active;
        this.debt = debt;
        this.creditDays = creditDays;
        this.creditLimit = creditLimit;
        this.initDate = initDate;
        this.rowguid = rowguid;
    }
    public CustomersId(int id, String name, String lastname, boolean active, boolean debt, int creditDays, BigDecimal creditLimit, Date initDate, Boolean incomplete, String code, Boolean retentionAgent, BigDecimal taxRetained, Date retentionAgentSince, String tag, Integer baseLocation, Integer correlative, String country, Boolean holdCustomsClearance, String invoicingComment, String rowguid, Date sop, Integer destinationCost, Boolean isCpsagent, Boolean airStorage, Boolean oceanStorage, Integer inlandPercentage, Boolean appliesTlc, String countriesList, Integer originCost) {
       this.id = id;
       this.name = name;
       this.lastname = lastname;
       this.active = active;
       this.debt = debt;
       this.creditDays = creditDays;
       this.creditLimit = creditLimit;
       this.initDate = initDate;
       this.incomplete = incomplete;
       this.code = code;
       this.retentionAgent = retentionAgent;
       this.taxRetained = taxRetained;
       this.retentionAgentSince = retentionAgentSince;
       this.tag = tag;
       this.baseLocation = baseLocation;
       this.correlative = correlative;
       this.country = country;
       this.holdCustomsClearance = holdCustomsClearance;
       this.invoicingComment = invoicingComment;
       this.rowguid = rowguid;
       this.sop = sop;
       this.destinationCost = destinationCost;
       this.isCpsagent = isCpsagent;
       this.airStorage = airStorage;
       this.oceanStorage = oceanStorage;
       this.inlandPercentage = inlandPercentage;
       this.appliesTlc = appliesTlc;
       this.countriesList = countriesList;
       this.originCost = originCost;
    }
   

    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Column(name="name", nullable=false, length=200)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Column(name="lastname", nullable=false, length=200)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }

    @Column(name="debt", nullable=false)
    public boolean isDebt() {
        return this.debt;
    }
    
    public void setDebt(boolean debt) {
        this.debt = debt;
    }

    @Column(name="creditDays", nullable=false)
    public int getCreditDays() {
        return this.creditDays;
    }
    
    public void setCreditDays(int creditDays) {
        this.creditDays = creditDays;
    }

    @Column(name="creditLimit", nullable=false, precision=18)
    public BigDecimal getCreditLimit() {
        return this.creditLimit;
    }
    
    public void setCreditLimit(BigDecimal creditLimit) {
        this.creditLimit = creditLimit;
    }

    @Column(name="initDate", nullable=false, length=23)
    public Date getInitDate() {
        return this.initDate;
    }
    
    public void setInitDate(Date initDate) {
        this.initDate = initDate;
    }

    @Column(name="incomplete")
    public Boolean getIncomplete() {
        return this.incomplete;
    }
    
    public void setIncomplete(Boolean incomplete) {
        this.incomplete = incomplete;
    }

    @Column(name="code", length=50)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    @Column(name="retentionAgent")
    public Boolean getRetentionAgent() {
        return this.retentionAgent;
    }
    
    public void setRetentionAgent(Boolean retentionAgent) {
        this.retentionAgent = retentionAgent;
    }

    @Column(name="taxRetained", precision=18)
    public BigDecimal getTaxRetained() {
        return this.taxRetained;
    }
    
    public void setTaxRetained(BigDecimal taxRetained) {
        this.taxRetained = taxRetained;
    }

    @Column(name="retentionAgentSince", length=23)
    public Date getRetentionAgentSince() {
        return this.retentionAgentSince;
    }
    
    public void setRetentionAgentSince(Date retentionAgentSince) {
        this.retentionAgentSince = retentionAgentSince;
    }

    @Column(name="tag", length=100)
    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }

    @Column(name="baseLocation")
    public Integer getBaseLocation() {
        return this.baseLocation;
    }
    
    public void setBaseLocation(Integer baseLocation) {
        this.baseLocation = baseLocation;
    }

    @Column(name="correlative")
    public Integer getCorrelative() {
        return this.correlative;
    }
    
    public void setCorrelative(Integer correlative) {
        this.correlative = correlative;
    }

    @Column(name="country", length=3)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    @Column(name="holdCustomsClearance")
    public Boolean getHoldCustomsClearance() {
        return this.holdCustomsClearance;
    }
    
    public void setHoldCustomsClearance(Boolean holdCustomsClearance) {
        this.holdCustomsClearance = holdCustomsClearance;
    }

    @Column(name="invoicingComment", length=250)
    public String getInvoicingComment() {
        return this.invoicingComment;
    }
    
    public void setInvoicingComment(String invoicingComment) {
        this.invoicingComment = invoicingComment;
    }

    @Column(name="rowguid", unique=true, nullable=false, length=36)
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }

    @Column(name="SOP", length=23)
    public Date getSop() {
        return this.sop;
    }
    
    public void setSop(Date sop) {
        this.sop = sop;
    }

    @Column(name="destinationCost")
    public Integer getDestinationCost() {
        return this.destinationCost;
    }
    
    public void setDestinationCost(Integer destinationCost) {
        this.destinationCost = destinationCost;
    }

    @Column(name="isCPSAgent")
    public Boolean getIsCpsagent() {
        return this.isCpsagent;
    }
    
    public void setIsCpsagent(Boolean isCpsagent) {
        this.isCpsagent = isCpsagent;
    }

    @Column(name="airStorage")
    public Boolean getAirStorage() {
        return this.airStorage;
    }
    
    public void setAirStorage(Boolean airStorage) {
        this.airStorage = airStorage;
    }

    @Column(name="oceanStorage")
    public Boolean getOceanStorage() {
        return this.oceanStorage;
    }
    
    public void setOceanStorage(Boolean oceanStorage) {
        this.oceanStorage = oceanStorage;
    }

    @Column(name="inlandPercentage")
    public Integer getInlandPercentage() {
        return this.inlandPercentage;
    }
    
    public void setInlandPercentage(Integer inlandPercentage) {
        this.inlandPercentage = inlandPercentage;
    }

    @Column(name="appliesTLC")
    public Boolean getAppliesTlc() {
        return this.appliesTlc;
    }
    
    public void setAppliesTlc(Boolean appliesTlc) {
        this.appliesTlc = appliesTlc;
    }

    @Column(name="countriesList", length=750)
    public String getCountriesList() {
        return this.countriesList;
    }
    
    public void setCountriesList(String countriesList) {
        this.countriesList = countriesList;
    }

    @Column(name="originCost")
    public Integer getOriginCost() {
        return this.originCost;
    }
    
    public void setOriginCost(Integer originCost) {
        this.originCost = originCost;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CustomersId) ) return false;
		 CustomersId castOther = ( CustomersId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getLastname()==castOther.getLastname()) || ( this.getLastname()!=null && castOther.getLastname()!=null && this.getLastname().equals(castOther.getLastname()) ) )
 && (this.isActive()==castOther.isActive())
 && (this.isDebt()==castOther.isDebt())
 && (this.getCreditDays()==castOther.getCreditDays())
 && ( (this.getCreditLimit()==castOther.getCreditLimit()) || ( this.getCreditLimit()!=null && castOther.getCreditLimit()!=null && this.getCreditLimit().equals(castOther.getCreditLimit()) ) )
 && ( (this.getInitDate()==castOther.getInitDate()) || ( this.getInitDate()!=null && castOther.getInitDate()!=null && this.getInitDate().equals(castOther.getInitDate()) ) )
 && ( (this.getIncomplete()==castOther.getIncomplete()) || ( this.getIncomplete()!=null && castOther.getIncomplete()!=null && this.getIncomplete().equals(castOther.getIncomplete()) ) )
 && ( (this.getCode()==castOther.getCode()) || ( this.getCode()!=null && castOther.getCode()!=null && this.getCode().equals(castOther.getCode()) ) )
 && ( (this.getRetentionAgent()==castOther.getRetentionAgent()) || ( this.getRetentionAgent()!=null && castOther.getRetentionAgent()!=null && this.getRetentionAgent().equals(castOther.getRetentionAgent()) ) )
 && ( (this.getTaxRetained()==castOther.getTaxRetained()) || ( this.getTaxRetained()!=null && castOther.getTaxRetained()!=null && this.getTaxRetained().equals(castOther.getTaxRetained()) ) )
 && ( (this.getRetentionAgentSince()==castOther.getRetentionAgentSince()) || ( this.getRetentionAgentSince()!=null && castOther.getRetentionAgentSince()!=null && this.getRetentionAgentSince().equals(castOther.getRetentionAgentSince()) ) )
 && ( (this.getTag()==castOther.getTag()) || ( this.getTag()!=null && castOther.getTag()!=null && this.getTag().equals(castOther.getTag()) ) )
 && ( (this.getBaseLocation()==castOther.getBaseLocation()) || ( this.getBaseLocation()!=null && castOther.getBaseLocation()!=null && this.getBaseLocation().equals(castOther.getBaseLocation()) ) )
 && ( (this.getCorrelative()==castOther.getCorrelative()) || ( this.getCorrelative()!=null && castOther.getCorrelative()!=null && this.getCorrelative().equals(castOther.getCorrelative()) ) )
 && ( (this.getCountry()==castOther.getCountry()) || ( this.getCountry()!=null && castOther.getCountry()!=null && this.getCountry().equals(castOther.getCountry()) ) )
 && ( (this.getHoldCustomsClearance()==castOther.getHoldCustomsClearance()) || ( this.getHoldCustomsClearance()!=null && castOther.getHoldCustomsClearance()!=null && this.getHoldCustomsClearance().equals(castOther.getHoldCustomsClearance()) ) )
 && ( (this.getInvoicingComment()==castOther.getInvoicingComment()) || ( this.getInvoicingComment()!=null && castOther.getInvoicingComment()!=null && this.getInvoicingComment().equals(castOther.getInvoicingComment()) ) )
 && ( (this.getRowguid()==castOther.getRowguid()) || ( this.getRowguid()!=null && castOther.getRowguid()!=null && this.getRowguid().equals(castOther.getRowguid()) ) )
 && ( (this.getSop()==castOther.getSop()) || ( this.getSop()!=null && castOther.getSop()!=null && this.getSop().equals(castOther.getSop()) ) )
 && ( (this.getDestinationCost()==castOther.getDestinationCost()) || ( this.getDestinationCost()!=null && castOther.getDestinationCost()!=null && this.getDestinationCost().equals(castOther.getDestinationCost()) ) )
 && ( (this.getIsCpsagent()==castOther.getIsCpsagent()) || ( this.getIsCpsagent()!=null && castOther.getIsCpsagent()!=null && this.getIsCpsagent().equals(castOther.getIsCpsagent()) ) )
 && ( (this.getAirStorage()==castOther.getAirStorage()) || ( this.getAirStorage()!=null && castOther.getAirStorage()!=null && this.getAirStorage().equals(castOther.getAirStorage()) ) )
 && ( (this.getOceanStorage()==castOther.getOceanStorage()) || ( this.getOceanStorage()!=null && castOther.getOceanStorage()!=null && this.getOceanStorage().equals(castOther.getOceanStorage()) ) )
 && ( (this.getInlandPercentage()==castOther.getInlandPercentage()) || ( this.getInlandPercentage()!=null && castOther.getInlandPercentage()!=null && this.getInlandPercentage().equals(castOther.getInlandPercentage()) ) )
 && ( (this.getAppliesTlc()==castOther.getAppliesTlc()) || ( this.getAppliesTlc()!=null && castOther.getAppliesTlc()!=null && this.getAppliesTlc().equals(castOther.getAppliesTlc()) ) )
 && ( (this.getCountriesList()==castOther.getCountriesList()) || ( this.getCountriesList()!=null && castOther.getCountriesList()!=null && this.getCountriesList().equals(castOther.getCountriesList()) ) )
 && ( (this.getOriginCost()==castOther.getOriginCost()) || ( this.getOriginCost()!=null && castOther.getOriginCost()!=null && this.getOriginCost().equals(castOther.getOriginCost()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getLastname() == null ? 0 : this.getLastname().hashCode() );
         result = 37 * result + (this.isActive()?1:0);
         result = 37 * result + (this.isDebt()?1:0);
         result = 37 * result + this.getCreditDays();
         result = 37 * result + ( getCreditLimit() == null ? 0 : this.getCreditLimit().hashCode() );
         result = 37 * result + ( getInitDate() == null ? 0 : this.getInitDate().hashCode() );
         result = 37 * result + ( getIncomplete() == null ? 0 : this.getIncomplete().hashCode() );
         result = 37 * result + ( getCode() == null ? 0 : this.getCode().hashCode() );
         result = 37 * result + ( getRetentionAgent() == null ? 0 : this.getRetentionAgent().hashCode() );
         result = 37 * result + ( getTaxRetained() == null ? 0 : this.getTaxRetained().hashCode() );
         result = 37 * result + ( getRetentionAgentSince() == null ? 0 : this.getRetentionAgentSince().hashCode() );
         result = 37 * result + ( getTag() == null ? 0 : this.getTag().hashCode() );
         result = 37 * result + ( getBaseLocation() == null ? 0 : this.getBaseLocation().hashCode() );
         result = 37 * result + ( getCorrelative() == null ? 0 : this.getCorrelative().hashCode() );
         result = 37 * result + ( getCountry() == null ? 0 : this.getCountry().hashCode() );
         result = 37 * result + ( getHoldCustomsClearance() == null ? 0 : this.getHoldCustomsClearance().hashCode() );
         result = 37 * result + ( getInvoicingComment() == null ? 0 : this.getInvoicingComment().hashCode() );
         result = 37 * result + ( getRowguid() == null ? 0 : this.getRowguid().hashCode() );
         result = 37 * result + ( getSop() == null ? 0 : this.getSop().hashCode() );
         result = 37 * result + ( getDestinationCost() == null ? 0 : this.getDestinationCost().hashCode() );
         result = 37 * result + ( getIsCpsagent() == null ? 0 : this.getIsCpsagent().hashCode() );
         result = 37 * result + ( getAirStorage() == null ? 0 : this.getAirStorage().hashCode() );
         result = 37 * result + ( getOceanStorage() == null ? 0 : this.getOceanStorage().hashCode() );
         result = 37 * result + ( getInlandPercentage() == null ? 0 : this.getInlandPercentage().hashCode() );
         result = 37 * result + ( getAppliesTlc() == null ? 0 : this.getAppliesTlc().hashCode() );
         result = 37 * result + ( getCountriesList() == null ? 0 : this.getCountriesList().hashCode() );
         result = 37 * result + ( getOriginCost() == null ? 0 : this.getOriginCost().hashCode() );
         return result;
   }   


}


