package beans;
// Generated Jul 16, 2009 12:30:56 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;

/**
 * Customers generated by hbm2java
 */
public class Customers  implements java.io.Serializable {


     private int id;
     private String name;
     private String lastname;
     private boolean active;
     private boolean debt;
     private int creditDays;
     private BigDecimal creditLimit;
     private Date initDate;
     private Boolean incomplete;
     private String rowguid;
     private String code;
     private Boolean retentionAgent;
     private BigDecimal taxRetained;
     private Date retentionAgentSince;
     private String tag;
     private Integer baseLocation;
     private Integer correlative;
     private String country;
     private Boolean holdCustomsClearance;

     private ArrayList<CustomerDestinations> customerDestinations = new ArrayList<CustomerDestinations>();

    public Customers() {
    }

	
    public Customers(int id, String name, String lastname, boolean active, boolean debt, int creditDays, BigDecimal creditLimit, Date initDate, String rowguid) {
        this.id = id;
        this.name = name;
        this.lastname = lastname;
        this.active = active;
        this.debt = debt;
        this.creditDays = creditDays;
        this.creditLimit = creditLimit;
        this.initDate = initDate;
        this.rowguid = rowguid;
    }
    public Customers(int id, String name, String lastname, boolean active, boolean debt, int creditDays, BigDecimal creditLimit, Date initDate, Boolean incomplete, String rowguid, String code, Boolean retentionAgent, BigDecimal taxRetained, Date retentionAgentSince, String tag, Integer baseLocation, Integer correlative, String country, Boolean holdCustomsClearance) {
       this.id = id;
       this.name = name;
       this.lastname = lastname;
       this.active = active;
       this.debt = debt;
       this.creditDays = creditDays;
       this.creditLimit = creditLimit;
       this.initDate = initDate;
       this.incomplete = incomplete;
       this.rowguid = rowguid;
       this.code = code;
       this.retentionAgent = retentionAgent;
       this.taxRetained = taxRetained;
       this.retentionAgentSince = retentionAgentSince;
       this.tag = tag;
       this.baseLocation = baseLocation;
       this.correlative = correlative;
       this.country = country;
       this.holdCustomsClearance = holdCustomsClearance;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public boolean isDebt() {
        return this.debt;
    }
    
    public void setDebt(boolean debt) {
        this.debt = debt;
    }
    public int getCreditDays() {
        return this.creditDays;
    }
    
    public void setCreditDays(int creditDays) {
        this.creditDays = creditDays;
    }
    public BigDecimal getCreditLimit() {
        return this.creditLimit;
    }
    
    public void setCreditLimit(BigDecimal creditLimit) {
        this.creditLimit = creditLimit;
    }
    public Date getInitDate() {
        return this.initDate;
    }
    
    public void setInitDate(Date initDate) {
        this.initDate = initDate;
    }
    public Boolean getIncomplete() {
        return this.incomplete;
    }
    
    public void setIncomplete(Boolean incomplete) {
        this.incomplete = incomplete;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Boolean getRetentionAgent() {
        return this.retentionAgent;
    }
    
    public void setRetentionAgent(Boolean retentionAgent) {
        this.retentionAgent = retentionAgent;
    }
    public BigDecimal getTaxRetained() {
        return this.taxRetained;
    }
    
    public void setTaxRetained(BigDecimal taxRetained) {
        this.taxRetained = taxRetained;
    }
    public Date getRetentionAgentSince() {
        return this.retentionAgentSince;
    }
    
    public void setRetentionAgentSince(Date retentionAgentSince) {
        this.retentionAgentSince = retentionAgentSince;
    }
    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }
    public Integer getBaseLocation() {
        return this.baseLocation;
    }
    
    public void setBaseLocation(Integer baseLocation) {
        this.baseLocation = baseLocation;
    }
    public Integer getCorrelative() {
        return this.correlative;
    }
    
    public void setCorrelative(Integer correlative) {
        this.correlative = correlative;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Boolean getHoldCustomsClearance() {
        return this.holdCustomsClearance;
    }
    
    public void setHoldCustomsClearance(Boolean holdCustomsClearance) {
        this.holdCustomsClearance = holdCustomsClearance;
    }

    public ArrayList<CustomerDestinations> getCustomerDestinations() {
        return customerDestinations;
    }

    public void setCustomerDestinations(ArrayList<CustomerDestinations> customerDestinations) {
        this.customerDestinations = customerDestinations;
    }
}


