package beans;
// Generated Jul 16, 2009 12:30:56 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * CustomerServices generated by hbm2java
 */
public class CustomerServices  implements java.io.Serializable {


     private int id;
     private int locationServiceId;
     private int customerDestinationId;
     private BigDecimal minimumCharge;
     private BigDecimal insurance;
     private BigDecimal insuranceCommission;
     private BigDecimal billOfLading;
     private BigDecimal awb;
     private BigDecimal handling;
     private BigDecimal localPickUp;
     private BigDecimal da;
     private BigDecimal inland;
     private BigDecimal securityCharge;
     private BigDecimal customsFee;
     private BigDecimal fuelSurcharge;
     private BigDecimal terminalFee;
     private BigDecimal freightFordwarder;
     private BigDecimal duty;
     private BigDecimal prepaidCharge;
     private String serviceNo;
     private String rowguid;
     private BigDecimal insuranceRate;
     private BigDecimal policyCharge;
     private Boolean allInclude;

     private LocationServices locationService;
     private CustomerChargesByLbs customerChargesByLbs;
     private CustomerChargesByCft customerChargesByCft;

    public CustomerServices() {
    }

	
    public CustomerServices(int id, int locationServiceId, int customerDestinationId, String rowguid) {
        this.id = id;
        this.locationServiceId = locationServiceId;
        this.customerDestinationId = customerDestinationId;
        this.rowguid = rowguid;
    }
    public CustomerServices(int id, int locationServiceId, int customerDestinationId, BigDecimal minimumCharge, BigDecimal insurance, BigDecimal insuranceCommission, BigDecimal billOfLading, BigDecimal awb, BigDecimal handling, BigDecimal localPickUp, BigDecimal da, BigDecimal inland, BigDecimal securityCharge, BigDecimal customsFee, BigDecimal fuelSurcharge, BigDecimal terminalFee, BigDecimal freightFordwarder, BigDecimal duty, BigDecimal prepaidCharge, String serviceNo, String rowguid, BigDecimal insuranceRate, BigDecimal policyCharge, Boolean allInclude) {
       this.id = id;
       this.locationServiceId = locationServiceId;
       this.customerDestinationId = customerDestinationId;
       this.minimumCharge = minimumCharge;
       this.insurance = insurance;
       this.insuranceCommission = insuranceCommission;
       this.billOfLading = billOfLading;
       this.awb = awb;
       this.handling = handling;
       this.localPickUp = localPickUp;
       this.da = da;
       this.inland = inland;
       this.securityCharge = securityCharge;
       this.customsFee = customsFee;
       this.fuelSurcharge = fuelSurcharge;
       this.terminalFee = terminalFee;
       this.freightFordwarder = freightFordwarder;
       this.duty = duty;
       this.prepaidCharge = prepaidCharge;
       this.serviceNo = serviceNo;
       this.rowguid = rowguid;
       this.insuranceRate = insuranceRate;
       this.policyCharge = policyCharge;
       this.allInclude = allInclude;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getLocationServiceId() {
        return this.locationServiceId;
    }
    
    public void setLocationServiceId(int locationServiceId) {
        this.locationServiceId = locationServiceId;
    }
    public int getCustomerDestinationId() {
        return this.customerDestinationId;
    }
    
    public void setCustomerDestinationId(int customerDestinationId) {
        this.customerDestinationId = customerDestinationId;
    }
    public BigDecimal getMinimumCharge() {
        return this.minimumCharge;
    }
    
    public void setMinimumCharge(BigDecimal minimumCharge) {
        this.minimumCharge = minimumCharge;
    }
    public BigDecimal getInsurance() {
        return this.insurance;
    }
    
    public void setInsurance(BigDecimal insurance) {
        this.insurance = insurance;
    }
    public BigDecimal getInsuranceCommission() {
        return this.insuranceCommission;
    }
    
    public void setInsuranceCommission(BigDecimal insuranceCommission) {
        this.insuranceCommission = insuranceCommission;
    }
    public BigDecimal getBillOfLading() {
        return this.billOfLading;
    }
    
    public void setBillOfLading(BigDecimal billOfLading) {
        this.billOfLading = billOfLading;
    }
    public BigDecimal getAwb() {
        return this.awb;
    }
    
    public void setAwb(BigDecimal awb) {
        this.awb = awb;
    }
    public BigDecimal getHandling() {
        return this.handling;
    }
    
    public void setHandling(BigDecimal handling) {
        this.handling = handling;
    }
    public BigDecimal getLocalPickUp() {
        return this.localPickUp;
    }
    
    public void setLocalPickUp(BigDecimal localPickUp) {
        this.localPickUp = localPickUp;
    }
    public BigDecimal getDa() {
        return this.da;
    }
    
    public void setDa(BigDecimal da) {
        this.da = da;
    }
    public BigDecimal getInland() {
        return this.inland;
    }
    
    public void setInland(BigDecimal inland) {
        this.inland = inland;
    }
    public BigDecimal getSecurityCharge() {
        return this.securityCharge;
    }
    
    public void setSecurityCharge(BigDecimal securityCharge) {
        this.securityCharge = securityCharge;
    }
    public BigDecimal getCustomsFee() {
        return this.customsFee;
    }
    
    public void setCustomsFee(BigDecimal customsFee) {
        this.customsFee = customsFee;
    }
    public BigDecimal getFuelSurcharge() {
        return this.fuelSurcharge;
    }
    
    public void setFuelSurcharge(BigDecimal fuelSurcharge) {
        this.fuelSurcharge = fuelSurcharge;
    }
    public BigDecimal getTerminalFee() {
        return this.terminalFee;
    }
    
    public void setTerminalFee(BigDecimal terminalFee) {
        this.terminalFee = terminalFee;
    }
    public BigDecimal getFreightFordwarder() {
        return this.freightFordwarder;
    }
    
    public void setFreightFordwarder(BigDecimal freightFordwarder) {
        this.freightFordwarder = freightFordwarder;
    }
    public BigDecimal getDuty() {
        return this.duty;
    }
    
    public void setDuty(BigDecimal duty) {
        this.duty = duty;
    }
    public BigDecimal getPrepaidCharge() {
        return this.prepaidCharge;
    }
    
    public void setPrepaidCharge(BigDecimal prepaidCharge) {
        this.prepaidCharge = prepaidCharge;
    }
    public String getServiceNo() {
        return this.serviceNo;
    }
    
    public void setServiceNo(String serviceNo) {
        this.serviceNo = serviceNo;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }
    public BigDecimal getInsuranceRate() {
        return this.insuranceRate;
    }
    
    public void setInsuranceRate(BigDecimal insuranceRate) {
        this.insuranceRate = insuranceRate;
    }
    public BigDecimal getPolicyCharge() {
        return this.policyCharge;
    }
    
    public void setPolicyCharge(BigDecimal policyCharge) {
        this.policyCharge = policyCharge;
    }
    public Boolean getAllInclude() {
        return this.allInclude;
    }
    
    public void setAllInclude(Boolean allInclude) {
        this.allInclude = allInclude;
    }

    public LocationServices getLocationService() {
        return locationService;
    }

    public void setLocationService(LocationServices locationService) {
        this.locationService = locationService;
    }

    public CustomerChargesByCft getCustomerChargesByCft() {
        return customerChargesByCft;
    }

    public void setCustomerChargesByCft(CustomerChargesByCft customerChargesByCft) {
        this.customerChargesByCft = customerChargesByCft;
    }

    public CustomerChargesByLbs getCustomerChargesByLbs() {
        return customerChargesByLbs;
    }

    public void setCustomerChargesByLbs(CustomerChargesByLbs customerChargesByLbs) {
        this.customerChargesByLbs = customerChargesByLbs;
    }
}


