package beans;
// Generated 16/05/2010 09:58:09 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DocumentTrackingId generated by hbm2java
 */
@Embeddable
public class DocumentTrackingId  implements java.io.Serializable {


     private int id;
     private String documentNo;
     private String documentType;
     private Integer userId;
     private Date trackingDate;
     private String message;
     private String action;
     private String type;
     private String dua;
     private String rowguid;

    public DocumentTrackingId() {
    }

	
    public DocumentTrackingId(int id, String rowguid) {
        this.id = id;
        this.rowguid = rowguid;
    }
    public DocumentTrackingId(int id, String documentNo, String documentType, Integer userId, Date trackingDate, String message, String action, String type, String dua, String rowguid) {
       this.id = id;
       this.documentNo = documentNo;
       this.documentType = documentType;
       this.userId = userId;
       this.trackingDate = trackingDate;
       this.message = message;
       this.action = action;
       this.type = type;
       this.dua = dua;
       this.rowguid = rowguid;
    }
   

    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Column(name="documentNo", length=50)
    public String getDocumentNo() {
        return this.documentNo;
    }
    
    public void setDocumentNo(String documentNo) {
        this.documentNo = documentNo;
    }

    @Column(name="documentType", length=10)
    public String getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }

    @Column(name="userId")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Column(name="trackingDate", length=23)
    public Date getTrackingDate() {
        return this.trackingDate;
    }
    
    public void setTrackingDate(Date trackingDate) {
        this.trackingDate = trackingDate;
    }

    @Column(name="message", length=500)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    @Column(name="action", length=20)
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }

    @Column(name="type", length=20)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    @Column(name="dua", length=50)
    public String getDua() {
        return this.dua;
    }
    
    public void setDua(String dua) {
        this.dua = dua;
    }

    @Column(name="rowguid", unique=true, nullable=false, length=36)
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DocumentTrackingId) ) return false;
		 DocumentTrackingId castOther = ( DocumentTrackingId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getDocumentNo()==castOther.getDocumentNo()) || ( this.getDocumentNo()!=null && castOther.getDocumentNo()!=null && this.getDocumentNo().equals(castOther.getDocumentNo()) ) )
 && ( (this.getDocumentType()==castOther.getDocumentType()) || ( this.getDocumentType()!=null && castOther.getDocumentType()!=null && this.getDocumentType().equals(castOther.getDocumentType()) ) )
 && ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getTrackingDate()==castOther.getTrackingDate()) || ( this.getTrackingDate()!=null && castOther.getTrackingDate()!=null && this.getTrackingDate().equals(castOther.getTrackingDate()) ) )
 && ( (this.getMessage()==castOther.getMessage()) || ( this.getMessage()!=null && castOther.getMessage()!=null && this.getMessage().equals(castOther.getMessage()) ) )
 && ( (this.getAction()==castOther.getAction()) || ( this.getAction()!=null && castOther.getAction()!=null && this.getAction().equals(castOther.getAction()) ) )
 && ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
 && ( (this.getDua()==castOther.getDua()) || ( this.getDua()!=null && castOther.getDua()!=null && this.getDua().equals(castOther.getDua()) ) )
 && ( (this.getRowguid()==castOther.getRowguid()) || ( this.getRowguid()!=null && castOther.getRowguid()!=null && this.getRowguid().equals(castOther.getRowguid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getDocumentNo() == null ? 0 : this.getDocumentNo().hashCode() );
         result = 37 * result + ( getDocumentType() == null ? 0 : this.getDocumentType().hashCode() );
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getTrackingDate() == null ? 0 : this.getTrackingDate().hashCode() );
         result = 37 * result + ( getMessage() == null ? 0 : this.getMessage().hashCode() );
         result = 37 * result + ( getAction() == null ? 0 : this.getAction().hashCode() );
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         result = 37 * result + ( getDua() == null ? 0 : this.getDua().hashCode() );
         result = 37 * result + ( getRowguid() == null ? 0 : this.getRowguid().hashCode() );
         return result;
   }   


}


