package beans;
// Generated Jul 23, 2009 10:55:21 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Documents generated by hbm2java
 */
public class Documents  implements java.io.Serializable {


     private int id;
     private String rowguid;
     private Date documentDate;
     private Integer origen;
     private Integer destination;
     private Integer agentOrigenId;
     private Integer agentDestinationId;
     private Integer customerId;
     private String description;
     private String routingId;
     private Integer totalPieces;
     private BigDecimal totalWeight;
     private BigDecimal totalVolWeight;
     private BigDecimal totalCft;
     private BigDecimal mercValue;
     private Boolean dangerousGoods;
     private String documentNo;
     private String documentType;
     private String refNo;
     private String poNumber;
     private String comment;
     private Integer shipperId;
     private String stepId;
     private String dua;
     private Integer mercValueCurrencyId;
     private Integer currencyId;
     private String measure;
     private BigDecimal docWeight;
     private BigDecimal docVolWeight;
     private BigDecimal exchangeRate;
     private BigDecimal docMercValue;
     private String baseDocType;
     private Date podDate;

     private Customers customer;
     private beans.Currencies currency;
     private String origenCityCode;
     private String destinationCityCode;
     private String origenName;
     private String destinationName;

    public Documents() {
    }

	
    public Documents(int id, String rowguid) {
        this.id = id;
        this.rowguid = rowguid;
    }
    public Documents(int id, String rowguid, Date documentDate, Integer origen, Integer destination, Integer agentOrigenId, Integer agentDestinationId, Integer customerId, String description, String routingId, Integer totalPieces, BigDecimal totalWeight, BigDecimal totalVolWeight, BigDecimal totalCft, BigDecimal mercValue, Boolean dangerousGoods, String documentNo, String documentType, String refNo, String poNumber, String comment, Integer shipperId, String stepId, String dua, Integer mercValueCurrencyId, Integer currencyId, String measure, BigDecimal docWeight, BigDecimal docVolWeight, BigDecimal exchangeRate, BigDecimal docMercValue, String baseDocType, Date podDate) {
       this.id = id;
       this.rowguid = rowguid;
       this.documentDate = documentDate;
       this.origen = origen;
       this.destination = destination;
       this.agentOrigenId = agentOrigenId;
       this.agentDestinationId = agentDestinationId;
       this.customerId = customerId;
       this.description = description;
       this.routingId = routingId;
       this.totalPieces = totalPieces;
       this.totalWeight = totalWeight;
       this.totalVolWeight = totalVolWeight;
       this.totalCft = totalCft;
       this.mercValue = mercValue;
       this.dangerousGoods = dangerousGoods;
       this.documentNo = documentNo;
       this.documentType = documentType;
       this.refNo = refNo;
       this.poNumber = poNumber;
       this.comment = comment;
       this.shipperId = shipperId;
       this.stepId = stepId;
       this.dua = dua;
       this.mercValueCurrencyId = mercValueCurrencyId;
       this.currencyId = currencyId;
       this.measure = measure;
       this.docWeight = docWeight;
       this.docVolWeight = docVolWeight;
       this.exchangeRate = exchangeRate;
       this.docMercValue = docMercValue;
       this.baseDocType = baseDocType;
       this.podDate = podDate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }
    public Date getDocumentDate() {
        return this.documentDate;
    }
    
    public void setDocumentDate(Date documentDate) {
        this.documentDate = documentDate;
    }
    public Integer getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(Integer origen) {
        this.origen = origen;
    }
    public Integer getDestination() {
        return this.destination;
    }
    
    public void setDestination(Integer destination) {
        this.destination = destination;
    }
    public Integer getAgentOrigenId() {
        return this.agentOrigenId;
    }
    
    public void setAgentOrigenId(Integer agentOrigenId) {
        this.agentOrigenId = agentOrigenId;
    }
    public Integer getAgentDestinationId() {
        return this.agentDestinationId;
    }
    
    public void setAgentDestinationId(Integer agentDestinationId) {
        this.agentDestinationId = agentDestinationId;
    }
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getRoutingId() {
        return this.routingId;
    }
    
    public void setRoutingId(String routingId) {
        this.routingId = routingId;
    }
    public Integer getTotalPieces() {
        return this.totalPieces;
    }
    
    public void setTotalPieces(Integer totalPieces) {
        this.totalPieces = totalPieces;
    }
    public BigDecimal getTotalWeight() {
        return this.totalWeight;
    }
    
    public void setTotalWeight(BigDecimal totalWeight) {
        this.totalWeight = totalWeight;
    }
    public BigDecimal getTotalVolWeight() {
        return this.totalVolWeight;
    }
    
    public void setTotalVolWeight(BigDecimal totalVolWeight) {
        this.totalVolWeight = totalVolWeight;
    }
    public BigDecimal getTotalCft() {
        return this.totalCft;
    }
    
    public void setTotalCft(BigDecimal totalCft) {
        this.totalCft = totalCft;
    }
    public BigDecimal getMercValue() {
        return this.mercValue;
    }
    
    public void setMercValue(BigDecimal mercValue) {
        this.mercValue = mercValue;
    }
    public Boolean getDangerousGoods() {
        return this.dangerousGoods;
    }
    
    public void setDangerousGoods(Boolean dangerousGoods) {
        this.dangerousGoods = dangerousGoods;
    }
    public String getDocumentNo() {
        return this.documentNo;
    }
    
    public void setDocumentNo(String documentNo) {
        this.documentNo = documentNo;
    }
    public String getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }
    public String getRefNo() {
        return this.refNo;
    }
    
    public void setRefNo(String refNo) {
        this.refNo = refNo;
    }
    public String getPoNumber() {
        return this.poNumber;
    }
    
    public void setPoNumber(String poNumber) {
        this.poNumber = poNumber;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Integer getShipperId() {
        return this.shipperId;
    }
    
    public void setShipperId(Integer shipperId) {
        this.shipperId = shipperId;
    }
    public String getStepId() {
        return this.stepId;
    }
    
    public void setStepId(String stepId) {
        this.stepId = stepId;
    }
    public String getDua() {
        return this.dua;
    }
    
    public void setDua(String dua) {
        this.dua = dua;
    }
    public Integer getMercValueCurrencyId() {
        return this.mercValueCurrencyId;
    }
    
    public void setMercValueCurrencyId(Integer mercValueCurrencyId) {
        this.mercValueCurrencyId = mercValueCurrencyId;
    }
    public Integer getCurrencyId() {
        return this.currencyId;
    }
    
    public void setCurrencyId(Integer currencyId) {
        this.currencyId = currencyId;
    }
    public String getMeasure() {
        return this.measure;
    }
    
    public void setMeasure(String measure) {
        this.measure = measure;
    }
    public BigDecimal getDocWeight() {
        return this.docWeight;
    }
    
    public void setDocWeight(BigDecimal docWeight) {
        this.docWeight = docWeight;
    }
    public BigDecimal getDocVolWeight() {
        return this.docVolWeight;
    }
    
    public void setDocVolWeight(BigDecimal docVolWeight) {
        this.docVolWeight = docVolWeight;
    }
    public BigDecimal getExchangeRate() {
        return this.exchangeRate;
    }
    
    public void setExchangeRate(BigDecimal exchangeRate) {
        this.exchangeRate = exchangeRate;
    }
    public BigDecimal getDocMercValue() {
        return this.docMercValue;
    }
    
    public void setDocMercValue(BigDecimal docMercValue) {
        this.docMercValue = docMercValue;
    }
    public String getBaseDocType() {
        return this.baseDocType;
    }
    
    public void setBaseDocType(String baseDocType) {
        this.baseDocType = baseDocType;
    }

    public String getDestinationCityCode() {
        return destinationCityCode;
    }

    public void setDestinationCityCode(String destinationCityCode) {
        this.destinationCityCode = destinationCityCode;
    }

    public String getOrigenCityCode() {
        return origenCityCode;
    }

    public void setOrigenCityCode(String origenCityCode) {
        this.origenCityCode = origenCityCode;
    }

    public String getDestinationName() {
        return destinationName;
    }

    public void setDestinationName(String destinationName) {
        this.destinationName = destinationName;
    }

    public String getOrigenName() {
        return origenName;
    }

    public void setOrigenName(String origenName) {
        this.origenName = origenName;
    }

    public Customers getCustomer() {
        return customer;
    }

    public void setCustomer(Customers customer) {
        this.customer = customer;
    }

    public Currencies getCurrency() {
        return currency;
    }

    public void setCurrency(Currencies currency) {
        this.currency = currency;
    }

    public Date getPodDate() {
        return podDate;
    }

    public void setPodDate(Date podDate) {
        this.podDate = podDate;
    }
}