package beans;
// Generated May 21, 2009 3:23:26 PM by Hibernate Tools 3.2.1.GA



/**
 * DocumentWarehouses generated by hbm2java
 */
public class DocumentWarehouses  implements java.io.Serializable {


     private int id;
     private Integer warehosueId;
     private Integer documentId;
     private String documentNo;
     private String rowguid;
     private String documentType;

    public DocumentWarehouses() {
    }

	
    public DocumentWarehouses(int id, String rowguid) {
        this.id = id;
        this.rowguid = rowguid;
    }
    public DocumentWarehouses(int id, Integer warehosueId, Integer documentId, String documentNo, String rowguid, String documentType) {
       this.id = id;
       this.warehosueId = warehosueId;
       this.documentId = documentId;
       this.documentNo = documentNo;
       this.rowguid = rowguid;
       this.documentType = documentType;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getWarehosueId() {
        return this.warehosueId;
    }
    
    public void setWarehosueId(Integer warehosueId) {
        this.warehosueId = warehosueId;
    }
    public Integer getDocumentId() {
        return this.documentId;
    }
    
    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }
    public String getDocumentNo() {
        return this.documentNo;
    }
    
    public void setDocumentNo(String documentNo) {
        this.documentNo = documentNo;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }
    public String getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }




}


