package beans;
// Generated 16/05/2010 09:58:09 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DocumentsId generated by hbm2java
 */
@Embeddable
public class DocumentsId  implements java.io.Serializable {


     private int id;
     private Date documentDate;
     private Integer origen;
     private Integer destination;
     private Integer agentOrigenId;
     private Integer agentDestinationId;
     private Integer customerId;
     private String description;
     private String routingId;
     private Integer totalPieces;
     private BigDecimal totalWeight;
     private BigDecimal totalVolWeight;
     private BigDecimal totalCft;
     private BigDecimal mercValue;
     private Boolean dangerousGoods;
     private String documentNo;
     private String documentType;
     private String refNo;
     private String poNumber;
     private String comment;
     private Integer shipperId;
     private String stepId;
     private String dua;
     private Integer mercValueCurrencyId;
     private Integer currencyId;
     private String measure;
     private BigDecimal docWeight;
     private BigDecimal docVolWeight;
     private BigDecimal exchangeRate;
     private BigDecimal docMercValue;
     private String baseDocType;
     private Date podDate;
     private String podName;
     private String rowguid;
     private BigDecimal cifValue;
     private BigDecimal daiValue;

    public DocumentsId() {
    }

	
    public DocumentsId(int id, String rowguid) {
        this.id = id;
        this.rowguid = rowguid;
    }
    public DocumentsId(int id, Date documentDate, Integer origen, Integer destination, Integer agentOrigenId, Integer agentDestinationId, Integer customerId, String description, String routingId, Integer totalPieces, BigDecimal totalWeight, BigDecimal totalVolWeight, BigDecimal totalCft, BigDecimal mercValue, Boolean dangerousGoods, String documentNo, String documentType, String refNo, String poNumber, String comment, Integer shipperId, String stepId, String dua, Integer mercValueCurrencyId, Integer currencyId, String measure, BigDecimal docWeight, BigDecimal docVolWeight, BigDecimal exchangeRate, BigDecimal docMercValue, String baseDocType, Date podDate, String podName, String rowguid, BigDecimal cifValue, BigDecimal daiValue) {
       this.id = id;
       this.documentDate = documentDate;
       this.origen = origen;
       this.destination = destination;
       this.agentOrigenId = agentOrigenId;
       this.agentDestinationId = agentDestinationId;
       this.customerId = customerId;
       this.description = description;
       this.routingId = routingId;
       this.totalPieces = totalPieces;
       this.totalWeight = totalWeight;
       this.totalVolWeight = totalVolWeight;
       this.totalCft = totalCft;
       this.mercValue = mercValue;
       this.dangerousGoods = dangerousGoods;
       this.documentNo = documentNo;
       this.documentType = documentType;
       this.refNo = refNo;
       this.poNumber = poNumber;
       this.comment = comment;
       this.shipperId = shipperId;
       this.stepId = stepId;
       this.dua = dua;
       this.mercValueCurrencyId = mercValueCurrencyId;
       this.currencyId = currencyId;
       this.measure = measure;
       this.docWeight = docWeight;
       this.docVolWeight = docVolWeight;
       this.exchangeRate = exchangeRate;
       this.docMercValue = docMercValue;
       this.baseDocType = baseDocType;
       this.podDate = podDate;
       this.podName = podName;
       this.rowguid = rowguid;
       this.cifValue = cifValue;
       this.daiValue = daiValue;
    }
   

    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Column(name="documentDate", length=23)
    public Date getDocumentDate() {
        return this.documentDate;
    }
    
    public void setDocumentDate(Date documentDate) {
        this.documentDate = documentDate;
    }

    @Column(name="origen")
    public Integer getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(Integer origen) {
        this.origen = origen;
    }

    @Column(name="destination")
    public Integer getDestination() {
        return this.destination;
    }
    
    public void setDestination(Integer destination) {
        this.destination = destination;
    }

    @Column(name="agentOrigenId")
    public Integer getAgentOrigenId() {
        return this.agentOrigenId;
    }
    
    public void setAgentOrigenId(Integer agentOrigenId) {
        this.agentOrigenId = agentOrigenId;
    }

    @Column(name="agentDestinationId")
    public Integer getAgentDestinationId() {
        return this.agentDestinationId;
    }
    
    public void setAgentDestinationId(Integer agentDestinationId) {
        this.agentDestinationId = agentDestinationId;
    }

    @Column(name="customerId")
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    @Column(name="description", length=300)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name="routingId", length=10)
    public String getRoutingId() {
        return this.routingId;
    }
    
    public void setRoutingId(String routingId) {
        this.routingId = routingId;
    }

    @Column(name="totalPieces")
    public Integer getTotalPieces() {
        return this.totalPieces;
    }
    
    public void setTotalPieces(Integer totalPieces) {
        this.totalPieces = totalPieces;
    }

    @Column(name="totalWeight", precision=18)
    public BigDecimal getTotalWeight() {
        return this.totalWeight;
    }
    
    public void setTotalWeight(BigDecimal totalWeight) {
        this.totalWeight = totalWeight;
    }

    @Column(name="totalVolWeight", precision=18)
    public BigDecimal getTotalVolWeight() {
        return this.totalVolWeight;
    }
    
    public void setTotalVolWeight(BigDecimal totalVolWeight) {
        this.totalVolWeight = totalVolWeight;
    }

    @Column(name="totalCft", precision=18)
    public BigDecimal getTotalCft() {
        return this.totalCft;
    }
    
    public void setTotalCft(BigDecimal totalCft) {
        this.totalCft = totalCft;
    }

    @Column(name="mercValue", precision=18)
    public BigDecimal getMercValue() {
        return this.mercValue;
    }
    
    public void setMercValue(BigDecimal mercValue) {
        this.mercValue = mercValue;
    }

    @Column(name="dangerousGoods")
    public Boolean getDangerousGoods() {
        return this.dangerousGoods;
    }
    
    public void setDangerousGoods(Boolean dangerousGoods) {
        this.dangerousGoods = dangerousGoods;
    }

    @Column(name="documentNo", length=50)
    public String getDocumentNo() {
        return this.documentNo;
    }
    
    public void setDocumentNo(String documentNo) {
        this.documentNo = documentNo;
    }

    @Column(name="documentType", length=10)
    public String getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }

    @Column(name="refNo", length=50)
    public String getRefNo() {
        return this.refNo;
    }
    
    public void setRefNo(String refNo) {
        this.refNo = refNo;
    }

    @Column(name="poNumber", length=50)
    public String getPoNumber() {
        return this.poNumber;
    }
    
    public void setPoNumber(String poNumber) {
        this.poNumber = poNumber;
    }

    @Column(name="comment", length=300)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    @Column(name="shipperId")
    public Integer getShipperId() {
        return this.shipperId;
    }
    
    public void setShipperId(Integer shipperId) {
        this.shipperId = shipperId;
    }

    @Column(name="stepId", length=2)
    public String getStepId() {
        return this.stepId;
    }
    
    public void setStepId(String stepId) {
        this.stepId = stepId;
    }

    @Column(name="dua", length=30)
    public String getDua() {
        return this.dua;
    }
    
    public void setDua(String dua) {
        this.dua = dua;
    }

    @Column(name="mercValueCurrencyId")
    public Integer getMercValueCurrencyId() {
        return this.mercValueCurrencyId;
    }
    
    public void setMercValueCurrencyId(Integer mercValueCurrencyId) {
        this.mercValueCurrencyId = mercValueCurrencyId;
    }

    @Column(name="currencyId")
    public Integer getCurrencyId() {
        return this.currencyId;
    }
    
    public void setCurrencyId(Integer currencyId) {
        this.currencyId = currencyId;
    }

    @Column(name="measure", length=3)
    public String getMeasure() {
        return this.measure;
    }
    
    public void setMeasure(String measure) {
        this.measure = measure;
    }

    @Column(name="docWeight", precision=18)
    public BigDecimal getDocWeight() {
        return this.docWeight;
    }
    
    public void setDocWeight(BigDecimal docWeight) {
        this.docWeight = docWeight;
    }

    @Column(name="docVolWeight", precision=18)
    public BigDecimal getDocVolWeight() {
        return this.docVolWeight;
    }
    
    public void setDocVolWeight(BigDecimal docVolWeight) {
        this.docVolWeight = docVolWeight;
    }

    @Column(name="exchangeRate", precision=18)
    public BigDecimal getExchangeRate() {
        return this.exchangeRate;
    }
    
    public void setExchangeRate(BigDecimal exchangeRate) {
        this.exchangeRate = exchangeRate;
    }

    @Column(name="docMercValue", precision=18)
    public BigDecimal getDocMercValue() {
        return this.docMercValue;
    }
    
    public void setDocMercValue(BigDecimal docMercValue) {
        this.docMercValue = docMercValue;
    }

    @Column(name="baseDocType", length=25)
    public String getBaseDocType() {
        return this.baseDocType;
    }
    
    public void setBaseDocType(String baseDocType) {
        this.baseDocType = baseDocType;
    }

    @Column(name="podDate", length=23)
    public Date getPodDate() {
        return this.podDate;
    }
    
    public void setPodDate(Date podDate) {
        this.podDate = podDate;
    }

    @Column(name="podName", length=250)
    public String getPodName() {
        return this.podName;
    }
    
    public void setPodName(String podName) {
        this.podName = podName;
    }

    @Column(name="rowguid", unique=true, nullable=false, length=36)
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }

    @Column(name="cifValue", precision=18)
    public BigDecimal getCifValue() {
        return this.cifValue;
    }
    
    public void setCifValue(BigDecimal cifValue) {
        this.cifValue = cifValue;
    }

    @Column(name="daiValue", precision=18)
    public BigDecimal getDaiValue() {
        return this.daiValue;
    }
    
    public void setDaiValue(BigDecimal daiValue) {
        this.daiValue = daiValue;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DocumentsId) ) return false;
		 DocumentsId castOther = ( DocumentsId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getDocumentDate()==castOther.getDocumentDate()) || ( this.getDocumentDate()!=null && castOther.getDocumentDate()!=null && this.getDocumentDate().equals(castOther.getDocumentDate()) ) )
 && ( (this.getOrigen()==castOther.getOrigen()) || ( this.getOrigen()!=null && castOther.getOrigen()!=null && this.getOrigen().equals(castOther.getOrigen()) ) )
 && ( (this.getDestination()==castOther.getDestination()) || ( this.getDestination()!=null && castOther.getDestination()!=null && this.getDestination().equals(castOther.getDestination()) ) )
 && ( (this.getAgentOrigenId()==castOther.getAgentOrigenId()) || ( this.getAgentOrigenId()!=null && castOther.getAgentOrigenId()!=null && this.getAgentOrigenId().equals(castOther.getAgentOrigenId()) ) )
 && ( (this.getAgentDestinationId()==castOther.getAgentDestinationId()) || ( this.getAgentDestinationId()!=null && castOther.getAgentDestinationId()!=null && this.getAgentDestinationId().equals(castOther.getAgentDestinationId()) ) )
 && ( (this.getCustomerId()==castOther.getCustomerId()) || ( this.getCustomerId()!=null && castOther.getCustomerId()!=null && this.getCustomerId().equals(castOther.getCustomerId()) ) )
 && ( (this.getDescription()==castOther.getDescription()) || ( this.getDescription()!=null && castOther.getDescription()!=null && this.getDescription().equals(castOther.getDescription()) ) )
 && ( (this.getRoutingId()==castOther.getRoutingId()) || ( this.getRoutingId()!=null && castOther.getRoutingId()!=null && this.getRoutingId().equals(castOther.getRoutingId()) ) )
 && ( (this.getTotalPieces()==castOther.getTotalPieces()) || ( this.getTotalPieces()!=null && castOther.getTotalPieces()!=null && this.getTotalPieces().equals(castOther.getTotalPieces()) ) )
 && ( (this.getTotalWeight()==castOther.getTotalWeight()) || ( this.getTotalWeight()!=null && castOther.getTotalWeight()!=null && this.getTotalWeight().equals(castOther.getTotalWeight()) ) )
 && ( (this.getTotalVolWeight()==castOther.getTotalVolWeight()) || ( this.getTotalVolWeight()!=null && castOther.getTotalVolWeight()!=null && this.getTotalVolWeight().equals(castOther.getTotalVolWeight()) ) )
 && ( (this.getTotalCft()==castOther.getTotalCft()) || ( this.getTotalCft()!=null && castOther.getTotalCft()!=null && this.getTotalCft().equals(castOther.getTotalCft()) ) )
 && ( (this.getMercValue()==castOther.getMercValue()) || ( this.getMercValue()!=null && castOther.getMercValue()!=null && this.getMercValue().equals(castOther.getMercValue()) ) )
 && ( (this.getDangerousGoods()==castOther.getDangerousGoods()) || ( this.getDangerousGoods()!=null && castOther.getDangerousGoods()!=null && this.getDangerousGoods().equals(castOther.getDangerousGoods()) ) )
 && ( (this.getDocumentNo()==castOther.getDocumentNo()) || ( this.getDocumentNo()!=null && castOther.getDocumentNo()!=null && this.getDocumentNo().equals(castOther.getDocumentNo()) ) )
 && ( (this.getDocumentType()==castOther.getDocumentType()) || ( this.getDocumentType()!=null && castOther.getDocumentType()!=null && this.getDocumentType().equals(castOther.getDocumentType()) ) )
 && ( (this.getRefNo()==castOther.getRefNo()) || ( this.getRefNo()!=null && castOther.getRefNo()!=null && this.getRefNo().equals(castOther.getRefNo()) ) )
 && ( (this.getPoNumber()==castOther.getPoNumber()) || ( this.getPoNumber()!=null && castOther.getPoNumber()!=null && this.getPoNumber().equals(castOther.getPoNumber()) ) )
 && ( (this.getComment()==castOther.getComment()) || ( this.getComment()!=null && castOther.getComment()!=null && this.getComment().equals(castOther.getComment()) ) )
 && ( (this.getShipperId()==castOther.getShipperId()) || ( this.getShipperId()!=null && castOther.getShipperId()!=null && this.getShipperId().equals(castOther.getShipperId()) ) )
 && ( (this.getStepId()==castOther.getStepId()) || ( this.getStepId()!=null && castOther.getStepId()!=null && this.getStepId().equals(castOther.getStepId()) ) )
 && ( (this.getDua()==castOther.getDua()) || ( this.getDua()!=null && castOther.getDua()!=null && this.getDua().equals(castOther.getDua()) ) )
 && ( (this.getMercValueCurrencyId()==castOther.getMercValueCurrencyId()) || ( this.getMercValueCurrencyId()!=null && castOther.getMercValueCurrencyId()!=null && this.getMercValueCurrencyId().equals(castOther.getMercValueCurrencyId()) ) )
 && ( (this.getCurrencyId()==castOther.getCurrencyId()) || ( this.getCurrencyId()!=null && castOther.getCurrencyId()!=null && this.getCurrencyId().equals(castOther.getCurrencyId()) ) )
 && ( (this.getMeasure()==castOther.getMeasure()) || ( this.getMeasure()!=null && castOther.getMeasure()!=null && this.getMeasure().equals(castOther.getMeasure()) ) )
 && ( (this.getDocWeight()==castOther.getDocWeight()) || ( this.getDocWeight()!=null && castOther.getDocWeight()!=null && this.getDocWeight().equals(castOther.getDocWeight()) ) )
 && ( (this.getDocVolWeight()==castOther.getDocVolWeight()) || ( this.getDocVolWeight()!=null && castOther.getDocVolWeight()!=null && this.getDocVolWeight().equals(castOther.getDocVolWeight()) ) )
 && ( (this.getExchangeRate()==castOther.getExchangeRate()) || ( this.getExchangeRate()!=null && castOther.getExchangeRate()!=null && this.getExchangeRate().equals(castOther.getExchangeRate()) ) )
 && ( (this.getDocMercValue()==castOther.getDocMercValue()) || ( this.getDocMercValue()!=null && castOther.getDocMercValue()!=null && this.getDocMercValue().equals(castOther.getDocMercValue()) ) )
 && ( (this.getBaseDocType()==castOther.getBaseDocType()) || ( this.getBaseDocType()!=null && castOther.getBaseDocType()!=null && this.getBaseDocType().equals(castOther.getBaseDocType()) ) )
 && ( (this.getPodDate()==castOther.getPodDate()) || ( this.getPodDate()!=null && castOther.getPodDate()!=null && this.getPodDate().equals(castOther.getPodDate()) ) )
 && ( (this.getPodName()==castOther.getPodName()) || ( this.getPodName()!=null && castOther.getPodName()!=null && this.getPodName().equals(castOther.getPodName()) ) )
 && ( (this.getRowguid()==castOther.getRowguid()) || ( this.getRowguid()!=null && castOther.getRowguid()!=null && this.getRowguid().equals(castOther.getRowguid()) ) )
 && ( (this.getCifValue()==castOther.getCifValue()) || ( this.getCifValue()!=null && castOther.getCifValue()!=null && this.getCifValue().equals(castOther.getCifValue()) ) )
 && ( (this.getDaiValue()==castOther.getDaiValue()) || ( this.getDaiValue()!=null && castOther.getDaiValue()!=null && this.getDaiValue().equals(castOther.getDaiValue()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getDocumentDate() == null ? 0 : this.getDocumentDate().hashCode() );
         result = 37 * result + ( getOrigen() == null ? 0 : this.getOrigen().hashCode() );
         result = 37 * result + ( getDestination() == null ? 0 : this.getDestination().hashCode() );
         result = 37 * result + ( getAgentOrigenId() == null ? 0 : this.getAgentOrigenId().hashCode() );
         result = 37 * result + ( getAgentDestinationId() == null ? 0 : this.getAgentDestinationId().hashCode() );
         result = 37 * result + ( getCustomerId() == null ? 0 : this.getCustomerId().hashCode() );
         result = 37 * result + ( getDescription() == null ? 0 : this.getDescription().hashCode() );
         result = 37 * result + ( getRoutingId() == null ? 0 : this.getRoutingId().hashCode() );
         result = 37 * result + ( getTotalPieces() == null ? 0 : this.getTotalPieces().hashCode() );
         result = 37 * result + ( getTotalWeight() == null ? 0 : this.getTotalWeight().hashCode() );
         result = 37 * result + ( getTotalVolWeight() == null ? 0 : this.getTotalVolWeight().hashCode() );
         result = 37 * result + ( getTotalCft() == null ? 0 : this.getTotalCft().hashCode() );
         result = 37 * result + ( getMercValue() == null ? 0 : this.getMercValue().hashCode() );
         result = 37 * result + ( getDangerousGoods() == null ? 0 : this.getDangerousGoods().hashCode() );
         result = 37 * result + ( getDocumentNo() == null ? 0 : this.getDocumentNo().hashCode() );
         result = 37 * result + ( getDocumentType() == null ? 0 : this.getDocumentType().hashCode() );
         result = 37 * result + ( getRefNo() == null ? 0 : this.getRefNo().hashCode() );
         result = 37 * result + ( getPoNumber() == null ? 0 : this.getPoNumber().hashCode() );
         result = 37 * result + ( getComment() == null ? 0 : this.getComment().hashCode() );
         result = 37 * result + ( getShipperId() == null ? 0 : this.getShipperId().hashCode() );
         result = 37 * result + ( getStepId() == null ? 0 : this.getStepId().hashCode() );
         result = 37 * result + ( getDua() == null ? 0 : this.getDua().hashCode() );
         result = 37 * result + ( getMercValueCurrencyId() == null ? 0 : this.getMercValueCurrencyId().hashCode() );
         result = 37 * result + ( getCurrencyId() == null ? 0 : this.getCurrencyId().hashCode() );
         result = 37 * result + ( getMeasure() == null ? 0 : this.getMeasure().hashCode() );
         result = 37 * result + ( getDocWeight() == null ? 0 : this.getDocWeight().hashCode() );
         result = 37 * result + ( getDocVolWeight() == null ? 0 : this.getDocVolWeight().hashCode() );
         result = 37 * result + ( getExchangeRate() == null ? 0 : this.getExchangeRate().hashCode() );
         result = 37 * result + ( getDocMercValue() == null ? 0 : this.getDocMercValue().hashCode() );
         result = 37 * result + ( getBaseDocType() == null ? 0 : this.getBaseDocType().hashCode() );
         result = 37 * result + ( getPodDate() == null ? 0 : this.getPodDate().hashCode() );
         result = 37 * result + ( getPodName() == null ? 0 : this.getPodName().hashCode() );
         result = 37 * result + ( getRowguid() == null ? 0 : this.getRowguid().hashCode() );
         result = 37 * result + ( getCifValue() == null ? 0 : this.getCifValue().hashCode() );
         result = 37 * result + ( getDaiValue() == null ? 0 : this.getDaiValue().hashCode() );
         return result;
   }   


}


