package beans;
// Generated May 21, 2009 3:23:26 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * DocumentTracking generated by hbm2java
 */
public class DocumentTracking  implements java.io.Serializable {


     private int id;
     private String documentNo;
     private String documentType;
     private Integer userId;
     private Date trackingDate;
     private String message;
     private String action;
     private String type;
     private String dua;
     private String rowguid;

    public DocumentTracking() {
    }

	
    public DocumentTracking(int id, String rowguid) {
        this.id = id;
        this.rowguid = rowguid;
    }
    public DocumentTracking(int id, String documentNo, String documentType, Integer userId, Date trackingDate, String message, String action, String type, String dua, String rowguid) {
       this.id = id;
       this.documentNo = documentNo;
       this.documentType = documentType;
       this.userId = userId;
       this.trackingDate = trackingDate;
       this.message = message;
       this.action = action;
       this.type = type;
       this.dua = dua;
       this.rowguid = rowguid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDocumentNo() {
        return this.documentNo;
    }
    
    public void setDocumentNo(String documentNo) {
        this.documentNo = documentNo;
    }
    public String getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Date getTrackingDate() {
        return this.trackingDate;
    }
    
    public void setTrackingDate(Date trackingDate) {
        this.trackingDate = trackingDate;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getDua() {
        return this.dua;
    }
    
    public void setDua(String dua) {
        this.dua = dua;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }




}


