package beans;
// Generated 16/05/2010 09:58:09 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocationRacksId generated by hbm2java
 */
@Embeddable
public class LocationRacksId  implements java.io.Serializable {


     private int id;
     private String name;
     private Integer positionNo;
     private String rowguid;

    public LocationRacksId() {
    }

	
    public LocationRacksId(int id, String name, String rowguid) {
        this.id = id;
        this.name = name;
        this.rowguid = rowguid;
    }
    public LocationRacksId(int id, String name, Integer positionNo, String rowguid) {
       this.id = id;
       this.name = name;
       this.positionNo = positionNo;
       this.rowguid = rowguid;
    }
   

    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Column(name="name", nullable=false, length=25)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Column(name="positionNo")
    public Integer getPositionNo() {
        return this.positionNo;
    }
    
    public void setPositionNo(Integer positionNo) {
        this.positionNo = positionNo;
    }

    @Column(name="rowguid", unique=true, nullable=false, length=36)
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LocationRacksId) ) return false;
		 LocationRacksId castOther = ( LocationRacksId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getPositionNo()==castOther.getPositionNo()) || ( this.getPositionNo()!=null && castOther.getPositionNo()!=null && this.getPositionNo().equals(castOther.getPositionNo()) ) )
 && ( (this.getRowguid()==castOther.getRowguid()) || ( this.getRowguid()!=null && castOther.getRowguid()!=null && this.getRowguid().equals(castOther.getRowguid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getPositionNo() == null ? 0 : this.getPositionNo().hashCode() );
         result = 37 * result + ( getRowguid() == null ? 0 : this.getRowguid().hashCode() );
         return result;
   }   


}


