package beans;
// Generated 16/05/2010 09:58:09 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocationsId generated by hbm2java
 */
@Embeddable
public class LocationsId  implements java.io.Serializable {


     private int id;
     private int cityId;
     private String name;
     private String email;
     private String tel;
     private String fax;
     private String logo;
     private String address;
     private String prefix;
     private Integer priority;
     private String rowguid;

    public LocationsId() {
    }

	
    public LocationsId(int id, int cityId, String name, String email, String tel, String fax, String logo, String address, String rowguid) {
        this.id = id;
        this.cityId = cityId;
        this.name = name;
        this.email = email;
        this.tel = tel;
        this.fax = fax;
        this.logo = logo;
        this.address = address;
        this.rowguid = rowguid;
    }
    public LocationsId(int id, int cityId, String name, String email, String tel, String fax, String logo, String address, String prefix, Integer priority, String rowguid) {
       this.id = id;
       this.cityId = cityId;
       this.name = name;
       this.email = email;
       this.tel = tel;
       this.fax = fax;
       this.logo = logo;
       this.address = address;
       this.prefix = prefix;
       this.priority = priority;
       this.rowguid = rowguid;
    }
   

    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Column(name="cityId", nullable=false)
    public int getCityId() {
        return this.cityId;
    }
    
    public void setCityId(int cityId) {
        this.cityId = cityId;
    }

    @Column(name="name", nullable=false, length=200)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name="tel", nullable=false, length=20)
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    @Column(name="fax", nullable=false, length=20)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    @Column(name="logo", nullable=false, length=100)
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }

    @Column(name="address", nullable=false, length=200)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name="prefix", length=3)
    public String getPrefix() {
        return this.prefix;
    }
    
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    @Column(name="priority")
    public Integer getPriority() {
        return this.priority;
    }
    
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    @Column(name="rowguid", unique=true, nullable=false, length=36)
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LocationsId) ) return false;
		 LocationsId castOther = ( LocationsId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getCityId()==castOther.getCityId())
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) )
 && ( (this.getTel()==castOther.getTel()) || ( this.getTel()!=null && castOther.getTel()!=null && this.getTel().equals(castOther.getTel()) ) )
 && ( (this.getFax()==castOther.getFax()) || ( this.getFax()!=null && castOther.getFax()!=null && this.getFax().equals(castOther.getFax()) ) )
 && ( (this.getLogo()==castOther.getLogo()) || ( this.getLogo()!=null && castOther.getLogo()!=null && this.getLogo().equals(castOther.getLogo()) ) )
 && ( (this.getAddress()==castOther.getAddress()) || ( this.getAddress()!=null && castOther.getAddress()!=null && this.getAddress().equals(castOther.getAddress()) ) )
 && ( (this.getPrefix()==castOther.getPrefix()) || ( this.getPrefix()!=null && castOther.getPrefix()!=null && this.getPrefix().equals(castOther.getPrefix()) ) )
 && ( (this.getPriority()==castOther.getPriority()) || ( this.getPriority()!=null && castOther.getPriority()!=null && this.getPriority().equals(castOther.getPriority()) ) )
 && ( (this.getRowguid()==castOther.getRowguid()) || ( this.getRowguid()!=null && castOther.getRowguid()!=null && this.getRowguid().equals(castOther.getRowguid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getCityId();
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         result = 37 * result + ( getTel() == null ? 0 : this.getTel().hashCode() );
         result = 37 * result + ( getFax() == null ? 0 : this.getFax().hashCode() );
         result = 37 * result + ( getLogo() == null ? 0 : this.getLogo().hashCode() );
         result = 37 * result + ( getAddress() == null ? 0 : this.getAddress().hashCode() );
         result = 37 * result + ( getPrefix() == null ? 0 : this.getPrefix().hashCode() );
         result = 37 * result + ( getPriority() == null ? 0 : this.getPriority().hashCode() );
         result = 37 * result + ( getRowguid() == null ? 0 : this.getRowguid().hashCode() );
         return result;
   }   


}


