package beans;
// Generated Jul 13, 2009 1:50:33 PM by Hibernate Tools 3.2.1.GA



/**
 * Messages generated by hbm2java
 */
public class Messages  implements java.io.Serializable {


     private int id;
     private String title;
     private String es;
     private String en;

    public Messages() {
    }

	
    public Messages(int id) {
        this.id = id;
    }
    public Messages(int id, String title, String es, String en) {
       this.id = id;
       this.title = title;
       this.es = es;
       this.en = en;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getEs() {
        return this.es;
    }
    
    public void setEs(String es) {
        this.es = es;
    }
    public String getEn() {
        return this.en;
    }
    
    public void setEn(String en) {
        this.en = en;
    }




}


