package beans;
// Generated Jul 14, 2009 11:04:33 AM by Hibernate Tools 3.2.1.GA



/**
 * Shippers generated by hbm2java
 */
public class Shippers  implements java.io.Serializable {


     private int id;
     private String name;
     private String address;
     private String city;
     private Integer stateId;
     private String zip;
     private String phone;
     private String contact;
     private String email;
     private String rowguid;

    public Shippers() {
    }

	
    public Shippers(int id, String name, String rowguid) {
        this.id = id;
        this.name = name;
        this.rowguid = rowguid;
    }
    public Shippers(int id, String name, String address, String city, Integer stateId, String zip, String phone, String contact, String email, String rowguid) {
       this.id = id;
       this.name = name;
       this.address = address;
       this.city = city;
       this.stateId = stateId;
       this.zip = zip;
       this.phone = phone;
       this.contact = contact;
       this.email = email;
       this.rowguid = rowguid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Integer getStateId() {
        return this.stateId;
    }
    
    public void setStateId(Integer stateId) {
        this.stateId = stateId;
    }
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }




}


