package beans;
// Generated Jul 29, 2009 4:29:55 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * TblCxcDetalleMovimientos generated by hbm2java
 */
public class TblCxcDetalleMovimientos  implements java.io.Serializable {


     private TblCxcDetalleMovimientosId id;
     private String idEjercicioFiscal;
     private int idMes;
     private Date fecha;
     private BigDecimal monto;
     private String idMoneda;
     private BigDecimal tasaCambio;
     private BigDecimal montoLocal;
     private int proximaLinea;
     private String observaciones;
     private Boolean afectaLibros;
     private Boolean enLibros;
     private Integer idTipoVenta;
     private BigDecimal valorVenta;
     private BigDecimal porcentaje;
     private BigDecimal valorIva;
     private Date fechaCreacion;

    public TblCxcDetalleMovimientos() {
    }

	
    public TblCxcDetalleMovimientos(TblCxcDetalleMovimientosId id, String idEjercicioFiscal, int idMes, Date fecha, BigDecimal monto, String idMoneda, BigDecimal tasaCambio, BigDecimal montoLocal, int proximaLinea, Date fechaCreacion) {
        this.id = id;
        this.idEjercicioFiscal = idEjercicioFiscal;
        this.idMes = idMes;
        this.fecha = fecha;
        this.monto = monto;
        this.idMoneda = idMoneda;
        this.tasaCambio = tasaCambio;
        this.montoLocal = montoLocal;
        this.proximaLinea = proximaLinea;
        this.fechaCreacion = fechaCreacion;
    }
    public TblCxcDetalleMovimientos(TblCxcDetalleMovimientosId id, String idEjercicioFiscal, int idMes, Date fecha, BigDecimal monto, String idMoneda, BigDecimal tasaCambio, BigDecimal montoLocal, int proximaLinea, String observaciones, Boolean afectaLibros, Boolean enLibros, Integer idTipoVenta, BigDecimal valorVenta, BigDecimal porcentaje, BigDecimal valorIva, Date fechaCreacion) {
       this.id = id;
       this.idEjercicioFiscal = idEjercicioFiscal;
       this.idMes = idMes;
       this.fecha = fecha;
       this.monto = monto;
       this.idMoneda = idMoneda;
       this.tasaCambio = tasaCambio;
       this.montoLocal = montoLocal;
       this.proximaLinea = proximaLinea;
       this.observaciones = observaciones;
       this.afectaLibros = afectaLibros;
       this.enLibros = enLibros;
       this.idTipoVenta = idTipoVenta;
       this.valorVenta = valorVenta;
       this.porcentaje = porcentaje;
       this.valorIva = valorIva;
       this.fechaCreacion = fechaCreacion;
    }
   
    public TblCxcDetalleMovimientosId getId() {
        return this.id;
    }
    
    public void setId(TblCxcDetalleMovimientosId id) {
        this.id = id;
    }
    public String getIdEjercicioFiscal() {
        return this.idEjercicioFiscal;
    }
    
    public void setIdEjercicioFiscal(String idEjercicioFiscal) {
        this.idEjercicioFiscal = idEjercicioFiscal;
    }
    public int getIdMes() {
        return this.idMes;
    }
    
    public void setIdMes(int idMes) {
        this.idMes = idMes;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public String getIdMoneda() {
        return this.idMoneda;
    }
    
    public void setIdMoneda(String idMoneda) {
        this.idMoneda = idMoneda;
    }
    public BigDecimal getTasaCambio() {
        return this.tasaCambio;
    }
    
    public void setTasaCambio(BigDecimal tasaCambio) {
        this.tasaCambio = tasaCambio;
    }
    public BigDecimal getMontoLocal() {
        return this.montoLocal;
    }
    
    public void setMontoLocal(BigDecimal montoLocal) {
        this.montoLocal = montoLocal;
    }
    public int getProximaLinea() {
        return this.proximaLinea;
    }
    
    public void setProximaLinea(int proximaLinea) {
        this.proximaLinea = proximaLinea;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Boolean getAfectaLibros() {
        return this.afectaLibros;
    }
    
    public void setAfectaLibros(Boolean afectaLibros) {
        this.afectaLibros = afectaLibros;
    }
    public Boolean getEnLibros() {
        return this.enLibros;
    }
    
    public void setEnLibros(Boolean enLibros) {
        this.enLibros = enLibros;
    }
    public Integer getIdTipoVenta() {
        return this.idTipoVenta;
    }
    
    public void setIdTipoVenta(Integer idTipoVenta) {
        this.idTipoVenta = idTipoVenta;
    }
    public BigDecimal getValorVenta() {
        return this.valorVenta;
    }
    
    public void setValorVenta(BigDecimal valorVenta) {
        this.valorVenta = valorVenta;
    }
    public BigDecimal getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(BigDecimal porcentaje) {
        this.porcentaje = porcentaje;
    }
    public BigDecimal getValorIva() {
        return this.valorIva;
    }
    
    public void setValorIva(BigDecimal valorIva) {
        this.valorIva = valorIva;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


