package beans;
// Generated 16/05/2010 09:58:09 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersId generated by hbm2java
 */
@Embeddable
public class UsersId  implements java.io.Serializable {


     private int id;
     private String username;
     private String password;
     private String name;
     private String lastname;
     private String email;
     private String email1;
     private String tel;
     private String cel;
     private String address;
     private int locationId;
     private Boolean customerAgent;
     private Boolean salesRepresentative;
     private String rowguid;
     private Boolean suspended;

    public UsersId() {
    }

	
    public UsersId(int id, String username, String name, String lastname, int locationId, String rowguid) {
        this.id = id;
        this.username = username;
        this.name = name;
        this.lastname = lastname;
        this.locationId = locationId;
        this.rowguid = rowguid;
    }
    public UsersId(int id, String username, String password, String name, String lastname, String email, String email1, String tel, String cel, String address, int locationId, Boolean customerAgent, Boolean salesRepresentative, String rowguid, Boolean suspended) {
       this.id = id;
       this.username = username;
       this.password = password;
       this.name = name;
       this.lastname = lastname;
       this.email = email;
       this.email1 = email1;
       this.tel = tel;
       this.cel = cel;
       this.address = address;
       this.locationId = locationId;
       this.customerAgent = customerAgent;
       this.salesRepresentative = salesRepresentative;
       this.rowguid = rowguid;
       this.suspended = suspended;
    }
   

    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Column(name="username", nullable=false, length=80)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name="password", length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Column(name="lastname", nullable=false, length=100)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Column(name="email", length=250)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="email1", length=250)
    public String getEmail1() {
        return this.email1;
    }
    
    public void setEmail1(String email1) {
        this.email1 = email1;
    }

    @Column(name="tel", length=20)
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    @Column(name="cel", length=20)
    public String getCel() {
        return this.cel;
    }
    
    public void setCel(String cel) {
        this.cel = cel;
    }

    @Column(name="address", length=300)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name="locationId", nullable=false)
    public int getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(int locationId) {
        this.locationId = locationId;
    }

    @Column(name="customerAgent")
    public Boolean getCustomerAgent() {
        return this.customerAgent;
    }
    
    public void setCustomerAgent(Boolean customerAgent) {
        this.customerAgent = customerAgent;
    }

    @Column(name="salesRepresentative")
    public Boolean getSalesRepresentative() {
        return this.salesRepresentative;
    }
    
    public void setSalesRepresentative(Boolean salesRepresentative) {
        this.salesRepresentative = salesRepresentative;
    }

    @Column(name="rowguid", unique=true, nullable=false, length=36)
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }

    @Column(name="suspended")
    public Boolean getSuspended() {
        return this.suspended;
    }
    
    public void setSuspended(Boolean suspended) {
        this.suspended = suspended;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsersId) ) return false;
		 UsersId castOther = ( UsersId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) )
 && ( (this.getPassword()==castOther.getPassword()) || ( this.getPassword()!=null && castOther.getPassword()!=null && this.getPassword().equals(castOther.getPassword()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getLastname()==castOther.getLastname()) || ( this.getLastname()!=null && castOther.getLastname()!=null && this.getLastname().equals(castOther.getLastname()) ) )
 && ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) )
 && ( (this.getTel()==castOther.getTel()) || ( this.getTel()!=null && castOther.getTel()!=null && this.getTel().equals(castOther.getTel()) ) )
 && ( (this.getCel()==castOther.getCel()) || ( this.getCel()!=null && castOther.getCel()!=null && this.getCel().equals(castOther.getCel()) ) )
 && ( (this.getAddress()==castOther.getAddress()) || ( this.getAddress()!=null && castOther.getAddress()!=null && this.getAddress().equals(castOther.getAddress()) ) )
 && (this.getLocationId()==castOther.getLocationId())
 && ( (this.getCustomerAgent()==castOther.getCustomerAgent()) || ( this.getCustomerAgent()!=null && castOther.getCustomerAgent()!=null && this.getCustomerAgent().equals(castOther.getCustomerAgent()) ) )
 && ( (this.getSalesRepresentative()==castOther.getSalesRepresentative()) || ( this.getSalesRepresentative()!=null && castOther.getSalesRepresentative()!=null && this.getSalesRepresentative().equals(castOther.getSalesRepresentative()) ) )
 && ( (this.getRowguid()==castOther.getRowguid()) || ( this.getRowguid()!=null && castOther.getRowguid()!=null && this.getRowguid().equals(castOther.getRowguid()) ) )
 && ( (this.getSuspended()==castOther.getSuspended()) || ( this.getSuspended()!=null && castOther.getSuspended()!=null && this.getSuspended().equals(castOther.getSuspended()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         result = 37 * result + ( getPassword() == null ? 0 : this.getPassword().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getLastname() == null ? 0 : this.getLastname().hashCode() );
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         result = 37 * result + ( getTel() == null ? 0 : this.getTel().hashCode() );
         result = 37 * result + ( getCel() == null ? 0 : this.getCel().hashCode() );
         result = 37 * result + ( getAddress() == null ? 0 : this.getAddress().hashCode() );
         result = 37 * result + this.getLocationId();
         result = 37 * result + ( getCustomerAgent() == null ? 0 : this.getCustomerAgent().hashCode() );
         result = 37 * result + ( getSalesRepresentative() == null ? 0 : this.getSalesRepresentative().hashCode() );
         result = 37 * result + ( getRowguid() == null ? 0 : this.getRowguid().hashCode() );
         result = 37 * result + ( getSuspended() == null ? 0 : this.getSuspended().hashCode() );
         return result;
   }   


}


