package beans;
// Generated Jul 14, 2009 5:00:07 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * WarehouseDetails generated by hbm2java
 */
public class WarehouseDetails  implements java.io.Serializable {


     private int id;
     private Integer warehouseId;
     private Integer pieces;
     private String packetTypeId;
     private BigDecimal length;
     private BigDecimal width;
     private BigDecimal height;
     private BigDecimal weight;
     private String rowguid;
     private String measure;

     private Double volWeight;
     private Double cft;

    public WarehouseDetails() {
    }

	
    public WarehouseDetails(int id, String rowguid) {
        this.id = id;
        this.rowguid = rowguid;
    }
    public WarehouseDetails(int id, Integer warehouseId, Integer pieces, String packetTypeId, BigDecimal length, BigDecimal width, BigDecimal height, BigDecimal weight, String rowguid, String measure) {
       this.id = id;
       this.warehouseId = warehouseId;
       this.pieces = pieces;
       this.packetTypeId = packetTypeId;
       this.length = length;
       this.width = width;
       this.height = height;
       this.weight = weight;
       this.rowguid = rowguid;
       this.measure = measure;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getWarehouseId() {
        return this.warehouseId;
    }
    
    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }
    public Integer getPieces() {
        return this.pieces;
    }
    
    public void setPieces(Integer pieces) {
        this.pieces = pieces;
    }
    public String getPacketTypeId() {
        return this.packetTypeId;
    }
    
    public void setPacketTypeId(String packetTypeId) {
        this.packetTypeId = packetTypeId;
    }
    public BigDecimal getLength() {
        return this.length;
    }
    
    public void setLength(BigDecimal length) {
        this.length = length;
    }
    public BigDecimal getWidth() {
        return this.width;
    }
    
    public void setWidth(BigDecimal width) {
        this.width = width;
    }
    public BigDecimal getHeight() {
        return this.height;
    }
    
    public void setHeight(BigDecimal height) {
        this.height = height;
    }
    public BigDecimal getWeight() {
        return this.weight;
    }
    
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }
    public String getMeasure() {
        return this.measure;
    }
    
    public void setMeasure(String measure) {
        this.measure = measure;
    }

    public Double getCft() {
        return cft;
    }

    public void setCft(Double cft) {
        this.cft = cft;
    }

    public Double getVolWeight() {
        return volWeight;
    }

    public void setVolWeight(Double volWeight) {
        this.volWeight = volWeight;
    }
}


