package beans;
// Generated 16/05/2010 09:58:09 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WarehousesId generated by hbm2java
 */
@Embeddable
public class WarehousesId  implements java.io.Serializable {


     private int id;
     private Integer customerId;
     private Integer shipperId;
     private String destinationId;
     private Date initDate;
     private String proNumber;
     private Integer inlandCarrierId;
     private Integer statusId;
     private Integer locationRackId;
     private String routingId;
     private String orderNo;
     private String refNo;
     private BigDecimal mercValue;
     private Boolean originalInvoice;
     private Boolean packingList;
     private String description;
     private String marks;
     private Boolean divided;
     private Boolean active;
     private int locationId;
     private String statusImage;
     private String stepId;
     private Integer customerDestinationId;
     private Integer locationServiceId;
     private Integer destinationLocationId;
     private Date routingDate;
     private Boolean dangerousGoods;
     private String locationRackComment;
     private Integer routingLocation;
     private String routingUser;
     private String currency;
     private String rowguid;

    public WarehousesId() {
    }

	
    public WarehousesId(int id, int locationId, String rowguid) {
        this.id = id;
        this.locationId = locationId;
        this.rowguid = rowguid;
    }
    public WarehousesId(int id, Integer customerId, Integer shipperId, String destinationId, Date initDate, String proNumber, Integer inlandCarrierId, Integer statusId, Integer locationRackId, String routingId, String orderNo, String refNo, BigDecimal mercValue, Boolean originalInvoice, Boolean packingList, String description, String marks, Boolean divided, Boolean active, int locationId, String statusImage, String stepId, Integer customerDestinationId, Integer locationServiceId, Integer destinationLocationId, Date routingDate, Boolean dangerousGoods, String locationRackComment, Integer routingLocation, String routingUser, String currency, String rowguid) {
       this.id = id;
       this.customerId = customerId;
       this.shipperId = shipperId;
       this.destinationId = destinationId;
       this.initDate = initDate;
       this.proNumber = proNumber;
       this.inlandCarrierId = inlandCarrierId;
       this.statusId = statusId;
       this.locationRackId = locationRackId;
       this.routingId = routingId;
       this.orderNo = orderNo;
       this.refNo = refNo;
       this.mercValue = mercValue;
       this.originalInvoice = originalInvoice;
       this.packingList = packingList;
       this.description = description;
       this.marks = marks;
       this.divided = divided;
       this.active = active;
       this.locationId = locationId;
       this.statusImage = statusImage;
       this.stepId = stepId;
       this.customerDestinationId = customerDestinationId;
       this.locationServiceId = locationServiceId;
       this.destinationLocationId = destinationLocationId;
       this.routingDate = routingDate;
       this.dangerousGoods = dangerousGoods;
       this.locationRackComment = locationRackComment;
       this.routingLocation = routingLocation;
       this.routingUser = routingUser;
       this.currency = currency;
       this.rowguid = rowguid;
    }
   

    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Column(name="customerId")
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    @Column(name="shipperId")
    public Integer getShipperId() {
        return this.shipperId;
    }
    
    public void setShipperId(Integer shipperId) {
        this.shipperId = shipperId;
    }

    @Column(name="destinationId", length=50)
    public String getDestinationId() {
        return this.destinationId;
    }
    
    public void setDestinationId(String destinationId) {
        this.destinationId = destinationId;
    }

    @Column(name="initDate", length=23)
    public Date getInitDate() {
        return this.initDate;
    }
    
    public void setInitDate(Date initDate) {
        this.initDate = initDate;
    }

    @Column(name="proNumber", length=100)
    public String getProNumber() {
        return this.proNumber;
    }
    
    public void setProNumber(String proNumber) {
        this.proNumber = proNumber;
    }

    @Column(name="inlandCarrierId")
    public Integer getInlandCarrierId() {
        return this.inlandCarrierId;
    }
    
    public void setInlandCarrierId(Integer inlandCarrierId) {
        this.inlandCarrierId = inlandCarrierId;
    }

    @Column(name="statusId")
    public Integer getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    @Column(name="locationRackId")
    public Integer getLocationRackId() {
        return this.locationRackId;
    }
    
    public void setLocationRackId(Integer locationRackId) {
        this.locationRackId = locationRackId;
    }

    @Column(name="routingId", length=3)
    public String getRoutingId() {
        return this.routingId;
    }
    
    public void setRoutingId(String routingId) {
        this.routingId = routingId;
    }

    @Column(name="orderNo", length=100)
    public String getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    @Column(name="refNo", length=100)
    public String getRefNo() {
        return this.refNo;
    }
    
    public void setRefNo(String refNo) {
        this.refNo = refNo;
    }

    @Column(name="mercValue", precision=18)
    public BigDecimal getMercValue() {
        return this.mercValue;
    }
    
    public void setMercValue(BigDecimal mercValue) {
        this.mercValue = mercValue;
    }

    @Column(name="originalInvoice")
    public Boolean getOriginalInvoice() {
        return this.originalInvoice;
    }
    
    public void setOriginalInvoice(Boolean originalInvoice) {
        this.originalInvoice = originalInvoice;
    }

    @Column(name="packingList")
    public Boolean getPackingList() {
        return this.packingList;
    }
    
    public void setPackingList(Boolean packingList) {
        this.packingList = packingList;
    }

    @Column(name="description", length=1000)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name="marks", length=2000)
    public String getMarks() {
        return this.marks;
    }
    
    public void setMarks(String marks) {
        this.marks = marks;
    }

    @Column(name="divided")
    public Boolean getDivided() {
        return this.divided;
    }
    
    public void setDivided(Boolean divided) {
        this.divided = divided;
    }

    @Column(name="active")
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }

    @Column(name="locationId", nullable=false)
    public int getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(int locationId) {
        this.locationId = locationId;
    }

    @Column(name="statusImage", length=50)
    public String getStatusImage() {
        return this.statusImage;
    }
    
    public void setStatusImage(String statusImage) {
        this.statusImage = statusImage;
    }

    @Column(name="stepId", length=2)
    public String getStepId() {
        return this.stepId;
    }
    
    public void setStepId(String stepId) {
        this.stepId = stepId;
    }

    @Column(name="customerDestinationId")
    public Integer getCustomerDestinationId() {
        return this.customerDestinationId;
    }
    
    public void setCustomerDestinationId(Integer customerDestinationId) {
        this.customerDestinationId = customerDestinationId;
    }

    @Column(name="locationServiceId")
    public Integer getLocationServiceId() {
        return this.locationServiceId;
    }
    
    public void setLocationServiceId(Integer locationServiceId) {
        this.locationServiceId = locationServiceId;
    }

    @Column(name="destinationLocationId")
    public Integer getDestinationLocationId() {
        return this.destinationLocationId;
    }
    
    public void setDestinationLocationId(Integer destinationLocationId) {
        this.destinationLocationId = destinationLocationId;
    }

    @Column(name="routingDate", length=23)
    public Date getRoutingDate() {
        return this.routingDate;
    }
    
    public void setRoutingDate(Date routingDate) {
        this.routingDate = routingDate;
    }

    @Column(name="dangerousGoods")
    public Boolean getDangerousGoods() {
        return this.dangerousGoods;
    }
    
    public void setDangerousGoods(Boolean dangerousGoods) {
        this.dangerousGoods = dangerousGoods;
    }

    @Column(name="locationRackComment", length=200)
    public String getLocationRackComment() {
        return this.locationRackComment;
    }
    
    public void setLocationRackComment(String locationRackComment) {
        this.locationRackComment = locationRackComment;
    }

    @Column(name="routingLocation")
    public Integer getRoutingLocation() {
        return this.routingLocation;
    }
    
    public void setRoutingLocation(Integer routingLocation) {
        this.routingLocation = routingLocation;
    }

    @Column(name="routingUser", length=50)
    public String getRoutingUser() {
        return this.routingUser;
    }
    
    public void setRoutingUser(String routingUser) {
        this.routingUser = routingUser;
    }

    @Column(name="currency", length=10)
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    @Column(name="rowguid", unique=true, nullable=false, length=36)
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WarehousesId) ) return false;
		 WarehousesId castOther = ( WarehousesId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getCustomerId()==castOther.getCustomerId()) || ( this.getCustomerId()!=null && castOther.getCustomerId()!=null && this.getCustomerId().equals(castOther.getCustomerId()) ) )
 && ( (this.getShipperId()==castOther.getShipperId()) || ( this.getShipperId()!=null && castOther.getShipperId()!=null && this.getShipperId().equals(castOther.getShipperId()) ) )
 && ( (this.getDestinationId()==castOther.getDestinationId()) || ( this.getDestinationId()!=null && castOther.getDestinationId()!=null && this.getDestinationId().equals(castOther.getDestinationId()) ) )
 && ( (this.getInitDate()==castOther.getInitDate()) || ( this.getInitDate()!=null && castOther.getInitDate()!=null && this.getInitDate().equals(castOther.getInitDate()) ) )
 && ( (this.getProNumber()==castOther.getProNumber()) || ( this.getProNumber()!=null && castOther.getProNumber()!=null && this.getProNumber().equals(castOther.getProNumber()) ) )
 && ( (this.getInlandCarrierId()==castOther.getInlandCarrierId()) || ( this.getInlandCarrierId()!=null && castOther.getInlandCarrierId()!=null && this.getInlandCarrierId().equals(castOther.getInlandCarrierId()) ) )
 && ( (this.getStatusId()==castOther.getStatusId()) || ( this.getStatusId()!=null && castOther.getStatusId()!=null && this.getStatusId().equals(castOther.getStatusId()) ) )
 && ( (this.getLocationRackId()==castOther.getLocationRackId()) || ( this.getLocationRackId()!=null && castOther.getLocationRackId()!=null && this.getLocationRackId().equals(castOther.getLocationRackId()) ) )
 && ( (this.getRoutingId()==castOther.getRoutingId()) || ( this.getRoutingId()!=null && castOther.getRoutingId()!=null && this.getRoutingId().equals(castOther.getRoutingId()) ) )
 && ( (this.getOrderNo()==castOther.getOrderNo()) || ( this.getOrderNo()!=null && castOther.getOrderNo()!=null && this.getOrderNo().equals(castOther.getOrderNo()) ) )
 && ( (this.getRefNo()==castOther.getRefNo()) || ( this.getRefNo()!=null && castOther.getRefNo()!=null && this.getRefNo().equals(castOther.getRefNo()) ) )
 && ( (this.getMercValue()==castOther.getMercValue()) || ( this.getMercValue()!=null && castOther.getMercValue()!=null && this.getMercValue().equals(castOther.getMercValue()) ) )
 && ( (this.getOriginalInvoice()==castOther.getOriginalInvoice()) || ( this.getOriginalInvoice()!=null && castOther.getOriginalInvoice()!=null && this.getOriginalInvoice().equals(castOther.getOriginalInvoice()) ) )
 && ( (this.getPackingList()==castOther.getPackingList()) || ( this.getPackingList()!=null && castOther.getPackingList()!=null && this.getPackingList().equals(castOther.getPackingList()) ) )
 && ( (this.getDescription()==castOther.getDescription()) || ( this.getDescription()!=null && castOther.getDescription()!=null && this.getDescription().equals(castOther.getDescription()) ) )
 && ( (this.getMarks()==castOther.getMarks()) || ( this.getMarks()!=null && castOther.getMarks()!=null && this.getMarks().equals(castOther.getMarks()) ) )
 && ( (this.getDivided()==castOther.getDivided()) || ( this.getDivided()!=null && castOther.getDivided()!=null && this.getDivided().equals(castOther.getDivided()) ) )
 && ( (this.getActive()==castOther.getActive()) || ( this.getActive()!=null && castOther.getActive()!=null && this.getActive().equals(castOther.getActive()) ) )
 && (this.getLocationId()==castOther.getLocationId())
 && ( (this.getStatusImage()==castOther.getStatusImage()) || ( this.getStatusImage()!=null && castOther.getStatusImage()!=null && this.getStatusImage().equals(castOther.getStatusImage()) ) )
 && ( (this.getStepId()==castOther.getStepId()) || ( this.getStepId()!=null && castOther.getStepId()!=null && this.getStepId().equals(castOther.getStepId()) ) )
 && ( (this.getCustomerDestinationId()==castOther.getCustomerDestinationId()) || ( this.getCustomerDestinationId()!=null && castOther.getCustomerDestinationId()!=null && this.getCustomerDestinationId().equals(castOther.getCustomerDestinationId()) ) )
 && ( (this.getLocationServiceId()==castOther.getLocationServiceId()) || ( this.getLocationServiceId()!=null && castOther.getLocationServiceId()!=null && this.getLocationServiceId().equals(castOther.getLocationServiceId()) ) )
 && ( (this.getDestinationLocationId()==castOther.getDestinationLocationId()) || ( this.getDestinationLocationId()!=null && castOther.getDestinationLocationId()!=null && this.getDestinationLocationId().equals(castOther.getDestinationLocationId()) ) )
 && ( (this.getRoutingDate()==castOther.getRoutingDate()) || ( this.getRoutingDate()!=null && castOther.getRoutingDate()!=null && this.getRoutingDate().equals(castOther.getRoutingDate()) ) )
 && ( (this.getDangerousGoods()==castOther.getDangerousGoods()) || ( this.getDangerousGoods()!=null && castOther.getDangerousGoods()!=null && this.getDangerousGoods().equals(castOther.getDangerousGoods()) ) )
 && ( (this.getLocationRackComment()==castOther.getLocationRackComment()) || ( this.getLocationRackComment()!=null && castOther.getLocationRackComment()!=null && this.getLocationRackComment().equals(castOther.getLocationRackComment()) ) )
 && ( (this.getRoutingLocation()==castOther.getRoutingLocation()) || ( this.getRoutingLocation()!=null && castOther.getRoutingLocation()!=null && this.getRoutingLocation().equals(castOther.getRoutingLocation()) ) )
 && ( (this.getRoutingUser()==castOther.getRoutingUser()) || ( this.getRoutingUser()!=null && castOther.getRoutingUser()!=null && this.getRoutingUser().equals(castOther.getRoutingUser()) ) )
 && ( (this.getCurrency()==castOther.getCurrency()) || ( this.getCurrency()!=null && castOther.getCurrency()!=null && this.getCurrency().equals(castOther.getCurrency()) ) )
 && ( (this.getRowguid()==castOther.getRowguid()) || ( this.getRowguid()!=null && castOther.getRowguid()!=null && this.getRowguid().equals(castOther.getRowguid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getCustomerId() == null ? 0 : this.getCustomerId().hashCode() );
         result = 37 * result + ( getShipperId() == null ? 0 : this.getShipperId().hashCode() );
         result = 37 * result + ( getDestinationId() == null ? 0 : this.getDestinationId().hashCode() );
         result = 37 * result + ( getInitDate() == null ? 0 : this.getInitDate().hashCode() );
         result = 37 * result + ( getProNumber() == null ? 0 : this.getProNumber().hashCode() );
         result = 37 * result + ( getInlandCarrierId() == null ? 0 : this.getInlandCarrierId().hashCode() );
         result = 37 * result + ( getStatusId() == null ? 0 : this.getStatusId().hashCode() );
         result = 37 * result + ( getLocationRackId() == null ? 0 : this.getLocationRackId().hashCode() );
         result = 37 * result + ( getRoutingId() == null ? 0 : this.getRoutingId().hashCode() );
         result = 37 * result + ( getOrderNo() == null ? 0 : this.getOrderNo().hashCode() );
         result = 37 * result + ( getRefNo() == null ? 0 : this.getRefNo().hashCode() );
         result = 37 * result + ( getMercValue() == null ? 0 : this.getMercValue().hashCode() );
         result = 37 * result + ( getOriginalInvoice() == null ? 0 : this.getOriginalInvoice().hashCode() );
         result = 37 * result + ( getPackingList() == null ? 0 : this.getPackingList().hashCode() );
         result = 37 * result + ( getDescription() == null ? 0 : this.getDescription().hashCode() );
         result = 37 * result + ( getMarks() == null ? 0 : this.getMarks().hashCode() );
         result = 37 * result + ( getDivided() == null ? 0 : this.getDivided().hashCode() );
         result = 37 * result + ( getActive() == null ? 0 : this.getActive().hashCode() );
         result = 37 * result + this.getLocationId();
         result = 37 * result + ( getStatusImage() == null ? 0 : this.getStatusImage().hashCode() );
         result = 37 * result + ( getStepId() == null ? 0 : this.getStepId().hashCode() );
         result = 37 * result + ( getCustomerDestinationId() == null ? 0 : this.getCustomerDestinationId().hashCode() );
         result = 37 * result + ( getLocationServiceId() == null ? 0 : this.getLocationServiceId().hashCode() );
         result = 37 * result + ( getDestinationLocationId() == null ? 0 : this.getDestinationLocationId().hashCode() );
         result = 37 * result + ( getRoutingDate() == null ? 0 : this.getRoutingDate().hashCode() );
         result = 37 * result + ( getDangerousGoods() == null ? 0 : this.getDangerousGoods().hashCode() );
         result = 37 * result + ( getLocationRackComment() == null ? 0 : this.getLocationRackComment().hashCode() );
         result = 37 * result + ( getRoutingLocation() == null ? 0 : this.getRoutingLocation().hashCode() );
         result = 37 * result + ( getRoutingUser() == null ? 0 : this.getRoutingUser().hashCode() );
         result = 37 * result + ( getCurrency() == null ? 0 : this.getCurrency().hashCode() );
         result = 37 * result + ( getRowguid() == null ? 0 : this.getRowguid().hashCode() );
         return result;
   }   


}


