package beans;
// Generated 16/05/2010 09:58:09 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CustomerServicesId generated by hbm2java
 */
@Embeddable
public class CustomerServicesId  implements java.io.Serializable {


     private int id;
     private int locationServiceId;
     private int customerDestinationId;
     private BigDecimal minimumCharge;
     private BigDecimal insurance;
     private BigDecimal insuranceCommission;
     private BigDecimal billOfLading;
     private BigDecimal awb;
     private BigDecimal handling;
     private BigDecimal localPickUp;
     private BigDecimal da;
     private BigDecimal inland;
     private BigDecimal securityCharge;
     private BigDecimal customsFee;
     private BigDecimal fuelSurcharge;
     private BigDecimal terminalFee;
     private BigDecimal freightFordwarder;
     private BigDecimal duty;
     private BigDecimal prepaidCharge;
     private String serviceNo;
     private BigDecimal insuranceRate;
     private BigDecimal policyCharge;
     private Boolean allInclude;
     private String rowguid;

    public CustomerServicesId() {
    }

	
    public CustomerServicesId(int id, int locationServiceId, int customerDestinationId, String rowguid) {
        this.id = id;
        this.locationServiceId = locationServiceId;
        this.customerDestinationId = customerDestinationId;
        this.rowguid = rowguid;
    }
    public CustomerServicesId(int id, int locationServiceId, int customerDestinationId, BigDecimal minimumCharge, BigDecimal insurance, BigDecimal insuranceCommission, BigDecimal billOfLading, BigDecimal awb, BigDecimal handling, BigDecimal localPickUp, BigDecimal da, BigDecimal inland, BigDecimal securityCharge, BigDecimal customsFee, BigDecimal fuelSurcharge, BigDecimal terminalFee, BigDecimal freightFordwarder, BigDecimal duty, BigDecimal prepaidCharge, String serviceNo, BigDecimal insuranceRate, BigDecimal policyCharge, Boolean allInclude, String rowguid) {
       this.id = id;
       this.locationServiceId = locationServiceId;
       this.customerDestinationId = customerDestinationId;
       this.minimumCharge = minimumCharge;
       this.insurance = insurance;
       this.insuranceCommission = insuranceCommission;
       this.billOfLading = billOfLading;
       this.awb = awb;
       this.handling = handling;
       this.localPickUp = localPickUp;
       this.da = da;
       this.inland = inland;
       this.securityCharge = securityCharge;
       this.customsFee = customsFee;
       this.fuelSurcharge = fuelSurcharge;
       this.terminalFee = terminalFee;
       this.freightFordwarder = freightFordwarder;
       this.duty = duty;
       this.prepaidCharge = prepaidCharge;
       this.serviceNo = serviceNo;
       this.insuranceRate = insuranceRate;
       this.policyCharge = policyCharge;
       this.allInclude = allInclude;
       this.rowguid = rowguid;
    }
   

    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Column(name="locationServiceId", nullable=false)
    public int getLocationServiceId() {
        return this.locationServiceId;
    }
    
    public void setLocationServiceId(int locationServiceId) {
        this.locationServiceId = locationServiceId;
    }

    @Column(name="customerDestinationId", nullable=false)
    public int getCustomerDestinationId() {
        return this.customerDestinationId;
    }
    
    public void setCustomerDestinationId(int customerDestinationId) {
        this.customerDestinationId = customerDestinationId;
    }

    @Column(name="minimumCharge", precision=18)
    public BigDecimal getMinimumCharge() {
        return this.minimumCharge;
    }
    
    public void setMinimumCharge(BigDecimal minimumCharge) {
        this.minimumCharge = minimumCharge;
    }

    @Column(name="insurance", precision=18)
    public BigDecimal getInsurance() {
        return this.insurance;
    }
    
    public void setInsurance(BigDecimal insurance) {
        this.insurance = insurance;
    }

    @Column(name="insuranceCommission", precision=18)
    public BigDecimal getInsuranceCommission() {
        return this.insuranceCommission;
    }
    
    public void setInsuranceCommission(BigDecimal insuranceCommission) {
        this.insuranceCommission = insuranceCommission;
    }

    @Column(name="billOfLading", precision=18)
    public BigDecimal getBillOfLading() {
        return this.billOfLading;
    }
    
    public void setBillOfLading(BigDecimal billOfLading) {
        this.billOfLading = billOfLading;
    }

    @Column(name="awb", precision=18)
    public BigDecimal getAwb() {
        return this.awb;
    }
    
    public void setAwb(BigDecimal awb) {
        this.awb = awb;
    }

    @Column(name="handling", precision=18)
    public BigDecimal getHandling() {
        return this.handling;
    }
    
    public void setHandling(BigDecimal handling) {
        this.handling = handling;
    }

    @Column(name="localPickUp", precision=18)
    public BigDecimal getLocalPickUp() {
        return this.localPickUp;
    }
    
    public void setLocalPickUp(BigDecimal localPickUp) {
        this.localPickUp = localPickUp;
    }

    @Column(name="DA", precision=18)
    public BigDecimal getDa() {
        return this.da;
    }
    
    public void setDa(BigDecimal da) {
        this.da = da;
    }

    @Column(name="inland", precision=18)
    public BigDecimal getInland() {
        return this.inland;
    }
    
    public void setInland(BigDecimal inland) {
        this.inland = inland;
    }

    @Column(name="securityCharge", precision=18)
    public BigDecimal getSecurityCharge() {
        return this.securityCharge;
    }
    
    public void setSecurityCharge(BigDecimal securityCharge) {
        this.securityCharge = securityCharge;
    }

    @Column(name="customsFee", precision=18)
    public BigDecimal getCustomsFee() {
        return this.customsFee;
    }
    
    public void setCustomsFee(BigDecimal customsFee) {
        this.customsFee = customsFee;
    }

    @Column(name="fuelSurcharge", precision=18)
    public BigDecimal getFuelSurcharge() {
        return this.fuelSurcharge;
    }
    
    public void setFuelSurcharge(BigDecimal fuelSurcharge) {
        this.fuelSurcharge = fuelSurcharge;
    }

    @Column(name="terminalFee", precision=18)
    public BigDecimal getTerminalFee() {
        return this.terminalFee;
    }
    
    public void setTerminalFee(BigDecimal terminalFee) {
        this.terminalFee = terminalFee;
    }

    @Column(name="freightFordwarder", precision=18)
    public BigDecimal getFreightFordwarder() {
        return this.freightFordwarder;
    }
    
    public void setFreightFordwarder(BigDecimal freightFordwarder) {
        this.freightFordwarder = freightFordwarder;
    }

    @Column(name="duty", precision=18)
    public BigDecimal getDuty() {
        return this.duty;
    }
    
    public void setDuty(BigDecimal duty) {
        this.duty = duty;
    }

    @Column(name="prepaidCharge", precision=18)
    public BigDecimal getPrepaidCharge() {
        return this.prepaidCharge;
    }
    
    public void setPrepaidCharge(BigDecimal prepaidCharge) {
        this.prepaidCharge = prepaidCharge;
    }

    @Column(name="serviceNo", length=50)
    public String getServiceNo() {
        return this.serviceNo;
    }
    
    public void setServiceNo(String serviceNo) {
        this.serviceNo = serviceNo;
    }

    @Column(name="insuranceRate", precision=18)
    public BigDecimal getInsuranceRate() {
        return this.insuranceRate;
    }
    
    public void setInsuranceRate(BigDecimal insuranceRate) {
        this.insuranceRate = insuranceRate;
    }

    @Column(name="policyCharge", precision=18)
    public BigDecimal getPolicyCharge() {
        return this.policyCharge;
    }
    
    public void setPolicyCharge(BigDecimal policyCharge) {
        this.policyCharge = policyCharge;
    }

    @Column(name="allInclude")
    public Boolean getAllInclude() {
        return this.allInclude;
    }
    
    public void setAllInclude(Boolean allInclude) {
        this.allInclude = allInclude;
    }

    @Column(name="rowguid", unique=true, nullable=false, length=36)
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CustomerServicesId) ) return false;
		 CustomerServicesId castOther = ( CustomerServicesId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getLocationServiceId()==castOther.getLocationServiceId())
 && (this.getCustomerDestinationId()==castOther.getCustomerDestinationId())
 && ( (this.getMinimumCharge()==castOther.getMinimumCharge()) || ( this.getMinimumCharge()!=null && castOther.getMinimumCharge()!=null && this.getMinimumCharge().equals(castOther.getMinimumCharge()) ) )
 && ( (this.getInsurance()==castOther.getInsurance()) || ( this.getInsurance()!=null && castOther.getInsurance()!=null && this.getInsurance().equals(castOther.getInsurance()) ) )
 && ( (this.getInsuranceCommission()==castOther.getInsuranceCommission()) || ( this.getInsuranceCommission()!=null && castOther.getInsuranceCommission()!=null && this.getInsuranceCommission().equals(castOther.getInsuranceCommission()) ) )
 && ( (this.getBillOfLading()==castOther.getBillOfLading()) || ( this.getBillOfLading()!=null && castOther.getBillOfLading()!=null && this.getBillOfLading().equals(castOther.getBillOfLading()) ) )
 && ( (this.getAwb()==castOther.getAwb()) || ( this.getAwb()!=null && castOther.getAwb()!=null && this.getAwb().equals(castOther.getAwb()) ) )
 && ( (this.getHandling()==castOther.getHandling()) || ( this.getHandling()!=null && castOther.getHandling()!=null && this.getHandling().equals(castOther.getHandling()) ) )
 && ( (this.getLocalPickUp()==castOther.getLocalPickUp()) || ( this.getLocalPickUp()!=null && castOther.getLocalPickUp()!=null && this.getLocalPickUp().equals(castOther.getLocalPickUp()) ) )
 && ( (this.getDa()==castOther.getDa()) || ( this.getDa()!=null && castOther.getDa()!=null && this.getDa().equals(castOther.getDa()) ) )
 && ( (this.getInland()==castOther.getInland()) || ( this.getInland()!=null && castOther.getInland()!=null && this.getInland().equals(castOther.getInland()) ) )
 && ( (this.getSecurityCharge()==castOther.getSecurityCharge()) || ( this.getSecurityCharge()!=null && castOther.getSecurityCharge()!=null && this.getSecurityCharge().equals(castOther.getSecurityCharge()) ) )
 && ( (this.getCustomsFee()==castOther.getCustomsFee()) || ( this.getCustomsFee()!=null && castOther.getCustomsFee()!=null && this.getCustomsFee().equals(castOther.getCustomsFee()) ) )
 && ( (this.getFuelSurcharge()==castOther.getFuelSurcharge()) || ( this.getFuelSurcharge()!=null && castOther.getFuelSurcharge()!=null && this.getFuelSurcharge().equals(castOther.getFuelSurcharge()) ) )
 && ( (this.getTerminalFee()==castOther.getTerminalFee()) || ( this.getTerminalFee()!=null && castOther.getTerminalFee()!=null && this.getTerminalFee().equals(castOther.getTerminalFee()) ) )
 && ( (this.getFreightFordwarder()==castOther.getFreightFordwarder()) || ( this.getFreightFordwarder()!=null && castOther.getFreightFordwarder()!=null && this.getFreightFordwarder().equals(castOther.getFreightFordwarder()) ) )
 && ( (this.getDuty()==castOther.getDuty()) || ( this.getDuty()!=null && castOther.getDuty()!=null && this.getDuty().equals(castOther.getDuty()) ) )
 && ( (this.getPrepaidCharge()==castOther.getPrepaidCharge()) || ( this.getPrepaidCharge()!=null && castOther.getPrepaidCharge()!=null && this.getPrepaidCharge().equals(castOther.getPrepaidCharge()) ) )
 && ( (this.getServiceNo()==castOther.getServiceNo()) || ( this.getServiceNo()!=null && castOther.getServiceNo()!=null && this.getServiceNo().equals(castOther.getServiceNo()) ) )
 && ( (this.getInsuranceRate()==castOther.getInsuranceRate()) || ( this.getInsuranceRate()!=null && castOther.getInsuranceRate()!=null && this.getInsuranceRate().equals(castOther.getInsuranceRate()) ) )
 && ( (this.getPolicyCharge()==castOther.getPolicyCharge()) || ( this.getPolicyCharge()!=null && castOther.getPolicyCharge()!=null && this.getPolicyCharge().equals(castOther.getPolicyCharge()) ) )
 && ( (this.getAllInclude()==castOther.getAllInclude()) || ( this.getAllInclude()!=null && castOther.getAllInclude()!=null && this.getAllInclude().equals(castOther.getAllInclude()) ) )
 && ( (this.getRowguid()==castOther.getRowguid()) || ( this.getRowguid()!=null && castOther.getRowguid()!=null && this.getRowguid().equals(castOther.getRowguid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getLocationServiceId();
         result = 37 * result + this.getCustomerDestinationId();
         result = 37 * result + ( getMinimumCharge() == null ? 0 : this.getMinimumCharge().hashCode() );
         result = 37 * result + ( getInsurance() == null ? 0 : this.getInsurance().hashCode() );
         result = 37 * result + ( getInsuranceCommission() == null ? 0 : this.getInsuranceCommission().hashCode() );
         result = 37 * result + ( getBillOfLading() == null ? 0 : this.getBillOfLading().hashCode() );
         result = 37 * result + ( getAwb() == null ? 0 : this.getAwb().hashCode() );
         result = 37 * result + ( getHandling() == null ? 0 : this.getHandling().hashCode() );
         result = 37 * result + ( getLocalPickUp() == null ? 0 : this.getLocalPickUp().hashCode() );
         result = 37 * result + ( getDa() == null ? 0 : this.getDa().hashCode() );
         result = 37 * result + ( getInland() == null ? 0 : this.getInland().hashCode() );
         result = 37 * result + ( getSecurityCharge() == null ? 0 : this.getSecurityCharge().hashCode() );
         result = 37 * result + ( getCustomsFee() == null ? 0 : this.getCustomsFee().hashCode() );
         result = 37 * result + ( getFuelSurcharge() == null ? 0 : this.getFuelSurcharge().hashCode() );
         result = 37 * result + ( getTerminalFee() == null ? 0 : this.getTerminalFee().hashCode() );
         result = 37 * result + ( getFreightFordwarder() == null ? 0 : this.getFreightFordwarder().hashCode() );
         result = 37 * result + ( getDuty() == null ? 0 : this.getDuty().hashCode() );
         result = 37 * result + ( getPrepaidCharge() == null ? 0 : this.getPrepaidCharge().hashCode() );
         result = 37 * result + ( getServiceNo() == null ? 0 : this.getServiceNo().hashCode() );
         result = 37 * result + ( getInsuranceRate() == null ? 0 : this.getInsuranceRate().hashCode() );
         result = 37 * result + ( getPolicyCharge() == null ? 0 : this.getPolicyCharge().hashCode() );
         result = 37 * result + ( getAllInclude() == null ? 0 : this.getAllInclude().hashCode() );
         result = 37 * result + ( getRowguid() == null ? 0 : this.getRowguid().hashCode() );
         return result;
   }   


}


