package beans;
// Generated Sep 10, 2014 4:21:47 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * MjFiles generated by hbm2java
 */
public class MjFiles  implements java.io.Serializable {


     private int id;
     private Date creationDate;
     private String name;
     private String url;
     private String comment;
     private String username;
     private String rowguid;
     private String correlative;

    public MjFiles() {
    }

	
    public MjFiles(int id, String rowguid) {
        this.id = id;
        this.rowguid = rowguid;
    }
    public MjFiles(int id, Date creationDate, String name, String url, String comment, String username, String rowguid, String correlative) {
       this.id = id;
       this.creationDate = creationDate;
       this.name = name;
       this.url = url;
       this.comment = comment;
       this.username = username;
       this.rowguid = rowguid;
       this.correlative = correlative;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }
    public String getCorrelative() {
        return this.correlative;
    }
    
    public void setCorrelative(String correlative) {
        this.correlative = correlative;
    }




}


