package beans;
// Generated May 21, 2009 3:23:26 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tracking generated by hbm2java
 */
public class Tracking  implements java.io.Serializable {


     private int id;
     private Date trackingDate;
     private Integer warehouseId;
     private String stepId;
     private String message;
     private String rowguid;

    public Tracking() {
    }

	
    public Tracking(int id, String rowguid) {
        this.id = id;
        this.rowguid = rowguid;
    }
    public Tracking(int id, Date trackingDate, Integer warehouseId, String stepId, String message, String rowguid) {
       this.id = id;
       this.trackingDate = trackingDate;
       this.warehouseId = warehouseId;
       this.stepId = stepId;
       this.message = message;
       this.rowguid = rowguid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getTrackingDate() {
        return this.trackingDate;
    }
    
    public void setTrackingDate(Date trackingDate) {
        this.trackingDate = trackingDate;
    }
    public Integer getWarehouseId() {
        return this.warehouseId;
    }
    
    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }
    public String getStepId() {
        return this.stepId;
    }
    
    public void setStepId(String stepId) {
        this.stepId = stepId;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }




}


