package beans;
// Generated Jul 29, 2009 4:29:55 PM by Hibernate Tools 3.2.1.GA



/**
 * TblCxcDetalleMovimientosId generated by hbm2java
 */
public class TblCxcDetalleMovimientosId  implements java.io.Serializable {


     private int idEmpresa;
     private int idVoucher;
     private int idTipoDocumento;
     private int idTipoMovimiento;
     private String noDocumento;
     private String serie;
     private int idCliente;
     private int cuota;

    public TblCxcDetalleMovimientosId() {
    }

    public TblCxcDetalleMovimientosId(int idEmpresa, int idVoucher, int idTipoDocumento, int idTipoMovimiento, String noDocumento, String serie, int idCliente, int cuota) {
       this.idEmpresa = idEmpresa;
       this.idVoucher = idVoucher;
       this.idTipoDocumento = idTipoDocumento;
       this.idTipoMovimiento = idTipoMovimiento;
       this.noDocumento = noDocumento;
       this.serie = serie;
       this.idCliente = idCliente;
       this.cuota = cuota;
    }
   
    public int getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public int getIdVoucher() {
        return this.idVoucher;
    }
    
    public void setIdVoucher(int idVoucher) {
        this.idVoucher = idVoucher;
    }
    public int getIdTipoDocumento() {
        return this.idTipoDocumento;
    }
    
    public void setIdTipoDocumento(int idTipoDocumento) {
        this.idTipoDocumento = idTipoDocumento;
    }
    public int getIdTipoMovimiento() {
        return this.idTipoMovimiento;
    }
    
    public void setIdTipoMovimiento(int idTipoMovimiento) {
        this.idTipoMovimiento = idTipoMovimiento;
    }
    public String getNoDocumento() {
        return this.noDocumento;
    }
    
    public void setNoDocumento(String noDocumento) {
        this.noDocumento = noDocumento;
    }
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public int getCuota() {
        return this.cuota;
    }
    
    public void setCuota(int cuota) {
        this.cuota = cuota;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblCxcDetalleMovimientosId) ) return false;
		 TblCxcDetalleMovimientosId castOther = ( TblCxcDetalleMovimientosId ) other; 
         
		 return (this.getIdEmpresa()==castOther.getIdEmpresa())
 && (this.getIdVoucher()==castOther.getIdVoucher())
 && (this.getIdTipoDocumento()==castOther.getIdTipoDocumento())
 && (this.getIdTipoMovimiento()==castOther.getIdTipoMovimiento())
 && ( (this.getNoDocumento()==castOther.getNoDocumento()) || ( this.getNoDocumento()!=null && castOther.getNoDocumento()!=null && this.getNoDocumento().equals(castOther.getNoDocumento()) ) )
 && ( (this.getSerie()==castOther.getSerie()) || ( this.getSerie()!=null && castOther.getSerie()!=null && this.getSerie().equals(castOther.getSerie()) ) )
 && (this.getIdCliente()==castOther.getIdCliente())
 && (this.getCuota()==castOther.getCuota());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEmpresa();
         result = 37 * result + this.getIdVoucher();
         result = 37 * result + this.getIdTipoDocumento();
         result = 37 * result + this.getIdTipoMovimiento();
         result = 37 * result + ( getNoDocumento() == null ? 0 : this.getNoDocumento().hashCode() );
         result = 37 * result + ( getSerie() == null ? 0 : this.getSerie().hashCode() );
         result = 37 * result + this.getIdCliente();
         result = 37 * result + this.getCuota();
         return result;
   }   


}


