package beans;
// Generated 16/05/2010 09:58:09 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CurrenciesId generated by hbm2java
 */
@Embeddable
public class CurrenciesId  implements java.io.Serializable {


     private int id;
     private String name;
     private String symbol;
     private String code;
     private String exchangeRate;
     private String rowguid;

    public CurrenciesId() {
    }

	
    public CurrenciesId(int id, String rowguid) {
        this.id = id;
        this.rowguid = rowguid;
    }
    public CurrenciesId(int id, String name, String symbol, String code, String exchangeRate, String rowguid) {
       this.id = id;
       this.name = name;
       this.symbol = symbol;
       this.code = code;
       this.exchangeRate = exchangeRate;
       this.rowguid = rowguid;
    }
   

    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Column(name="symbol", length=3)
    public String getSymbol() {
        return this.symbol;
    }
    
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    @Column(name="code", length=3)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    @Column(name="exchangeRate", length=3)
    public String getExchangeRate() {
        return this.exchangeRate;
    }
    
    public void setExchangeRate(String exchangeRate) {
        this.exchangeRate = exchangeRate;
    }

    @Column(name="rowguid", unique=true, nullable=false, length=36)
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CurrenciesId) ) return false;
		 CurrenciesId castOther = ( CurrenciesId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getSymbol()==castOther.getSymbol()) || ( this.getSymbol()!=null && castOther.getSymbol()!=null && this.getSymbol().equals(castOther.getSymbol()) ) )
 && ( (this.getCode()==castOther.getCode()) || ( this.getCode()!=null && castOther.getCode()!=null && this.getCode().equals(castOther.getCode()) ) )
 && ( (this.getExchangeRate()==castOther.getExchangeRate()) || ( this.getExchangeRate()!=null && castOther.getExchangeRate()!=null && this.getExchangeRate().equals(castOther.getExchangeRate()) ) )
 && ( (this.getRowguid()==castOther.getRowguid()) || ( this.getRowguid()!=null && castOther.getRowguid()!=null && this.getRowguid().equals(castOther.getRowguid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getSymbol() == null ? 0 : this.getSymbol().hashCode() );
         result = 37 * result + ( getCode() == null ? 0 : this.getCode().hashCode() );
         result = 37 * result + ( getExchangeRate() == null ? 0 : this.getExchangeRate().hashCode() );
         result = 37 * result + ( getRowguid() == null ? 0 : this.getRowguid().hashCode() );
         return result;
   }   


}


