package beans;
// Generated Jul 16, 2009 2:28:41 PM by Hibernate Tools 3.2.1.GA



/**
 * Locations generated by hbm2java
 */
public class Locations  implements java.io.Serializable {


     private int id;
     private int cityId;
     private String name;
     private String email;
     private String tel;
     private String fax;
     private String logo;
     private String address;
     private String rowguid;
     private String prefix;
     private Integer priority;

    public Locations() {
    }

	
    public Locations(int id, int cityId, String name, String email, String tel, String fax, String logo, String address, String rowguid) {
        this.id = id;
        this.cityId = cityId;
        this.name = name;
        this.email = email;
        this.tel = tel;
        this.fax = fax;
        this.logo = logo;
        this.address = address;
        this.rowguid = rowguid;
    }
    public Locations(int id, int cityId, String name, String email, String tel, String fax, String logo, String address, String rowguid, String prefix, Integer priority) {
       this.id = id;
       this.cityId = cityId;
       this.name = name;
       this.email = email;
       this.tel = tel;
       this.fax = fax;
       this.logo = logo;
       this.address = address;
       this.rowguid = rowguid;
       this.prefix = prefix;
       this.priority = priority;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getCityId() {
        return this.cityId;
    }
    
    public void setCityId(int cityId) {
        this.cityId = cityId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }
    public String getPrefix() {
        return this.prefix;
    }
    
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }
    public Integer getPriority() {
        return this.priority;
    }
    
    public void setPriority(Integer priority) {
        this.priority = priority;
    }




}


