package beans;
// Generated 16/05/2010 09:58:09 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DocumentWarehousesId generated by hbm2java
 */
@Embeddable
public class DocumentWarehousesId  implements java.io.Serializable {


     private int id;
     private Integer warehosueId;
     private Integer documentId;
     private String documentNo;
     private String documentType;
     private String rowguid;

    public DocumentWarehousesId() {
    }

	
    public DocumentWarehousesId(int id, String rowguid) {
        this.id = id;
        this.rowguid = rowguid;
    }
    public DocumentWarehousesId(int id, Integer warehosueId, Integer documentId, String documentNo, String documentType, String rowguid) {
       this.id = id;
       this.warehosueId = warehosueId;
       this.documentId = documentId;
       this.documentNo = documentNo;
       this.documentType = documentType;
       this.rowguid = rowguid;
    }
   

    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Column(name="warehosueId")
    public Integer getWarehosueId() {
        return this.warehosueId;
    }
    
    public void setWarehosueId(Integer warehosueId) {
        this.warehosueId = warehosueId;
    }

    @Column(name="documentId")
    public Integer getDocumentId() {
        return this.documentId;
    }
    
    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

    @Column(name="documentNo", length=50)
    public String getDocumentNo() {
        return this.documentNo;
    }
    
    public void setDocumentNo(String documentNo) {
        this.documentNo = documentNo;
    }

    @Column(name="documentType", length=10)
    public String getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }

    @Column(name="rowguid", unique=true, nullable=false, length=36)
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DocumentWarehousesId) ) return false;
		 DocumentWarehousesId castOther = ( DocumentWarehousesId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getWarehosueId()==castOther.getWarehosueId()) || ( this.getWarehosueId()!=null && castOther.getWarehosueId()!=null && this.getWarehosueId().equals(castOther.getWarehosueId()) ) )
 && ( (this.getDocumentId()==castOther.getDocumentId()) || ( this.getDocumentId()!=null && castOther.getDocumentId()!=null && this.getDocumentId().equals(castOther.getDocumentId()) ) )
 && ( (this.getDocumentNo()==castOther.getDocumentNo()) || ( this.getDocumentNo()!=null && castOther.getDocumentNo()!=null && this.getDocumentNo().equals(castOther.getDocumentNo()) ) )
 && ( (this.getDocumentType()==castOther.getDocumentType()) || ( this.getDocumentType()!=null && castOther.getDocumentType()!=null && this.getDocumentType().equals(castOther.getDocumentType()) ) )
 && ( (this.getRowguid()==castOther.getRowguid()) || ( this.getRowguid()!=null && castOther.getRowguid()!=null && this.getRowguid().equals(castOther.getRowguid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getWarehosueId() == null ? 0 : this.getWarehosueId().hashCode() );
         result = 37 * result + ( getDocumentId() == null ? 0 : this.getDocumentId().hashCode() );
         result = 37 * result + ( getDocumentNo() == null ? 0 : this.getDocumentNo().hashCode() );
         result = 37 * result + ( getDocumentType() == null ? 0 : this.getDocumentType().hashCode() );
         result = 37 * result + ( getRowguid() == null ? 0 : this.getRowguid().hashCode() );
         return result;
   }   


}


