package beans;
// Generated Jul 14, 2009 4:46:27 PM by Hibernate Tools 3.2.1.GA



/**
 * Cities generated by hbm2java
 */
public class Cities  implements java.io.Serializable {


     private int id;
     private String stateId;
     private String code;
     private String name;
     private String rowguid;

    public Cities() {
    }

    public Cities(int id, String stateId, String code, String name, String rowguid) {
       this.id = id;
       this.stateId = stateId;
       this.code = code;
       this.name = name;
       this.rowguid = rowguid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getStateId() {
        return this.stateId;
    }
    
    public void setStateId(String stateId) {
        this.stateId = stateId;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }




}


