package beans;
// Generated May 22, 2009 9:08:04 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * WarehouseTracking generated by hbm2java
 */
public class WarehouseTracking  implements java.io.Serializable {


     private int id;
     private Date hour;
     private Integer difference;
     private Integer warehouseId;
     private String tracking;
     private String rowguid;

    public WarehouseTracking() {
    }

	
    public WarehouseTracking(int id, String rowguid) {
        this.id = id;
        this.rowguid = rowguid;
    }
    public WarehouseTracking(int id, Date hour, Integer difference, Integer warehouseId, String tracking, String rowguid) {
       this.id = id;
       this.hour = hour;
       this.difference = difference;
       this.warehouseId = warehouseId;
       this.tracking = tracking;
       this.rowguid = rowguid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getHour() {
        return this.hour;
    }
    
    public void setHour(Date hour) {
        this.hour = hour;
    }
    public Integer getDifference() {
        return this.difference;
    }
    
    public void setDifference(Integer difference) {
        this.difference = difference;
    }
    public Integer getWarehouseId() {
        return this.warehouseId;
    }
    
    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }
    public String getTracking() {
        return this.tracking;
    }
    
    public void setTracking(String tracking) {
        this.tracking = tracking;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }




}


