package beans;
// Generated Jul 17, 2009 9:34:15 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * CustomerChargesByLbs generated by hbm2java
 */
public class CustomerChargesByLbs  implements java.io.Serializable {


     private int id;
     private int chargesByLbsId;
     private BigDecimal flatFee;
     private String rowguid;

    public CustomerChargesByLbs() {
    }

	
    public CustomerChargesByLbs(int id, int chargesByLbsId, String rowguid) {
        this.id = id;
        this.chargesByLbsId = chargesByLbsId;
        this.rowguid = rowguid;
    }
    public CustomerChargesByLbs(int id, int chargesByLbsId, BigDecimal flatFee, String rowguid) {
       this.id = id;
       this.chargesByLbsId = chargesByLbsId;
       this.flatFee = flatFee;
       this.rowguid = rowguid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getChargesByLbsId() {
        return this.chargesByLbsId;
    }
    
    public void setChargesByLbsId(int chargesByLbsId) {
        this.chargesByLbsId = chargesByLbsId;
    }
    public BigDecimal getFlatFee() {
        return this.flatFee;
    }
    
    public void setFlatFee(BigDecimal flatFee) {
        this.flatFee = flatFee;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }




}


