package beans;
// Generated Jul 21, 2009 2:25:20 PM by Hibernate Tools 3.2.1.GA



/**
 * LocationRacks generated by hbm2java
 */
public class LocationRacks  implements java.io.Serializable {


     private int id;
     private String name;
     private Integer positionNo;
     private String rowguid;

    public LocationRacks() {
    }

	
    public LocationRacks(int id, String name, String rowguid) {
        this.id = id;
        this.name = name;
        this.rowguid = rowguid;
    }
    public LocationRacks(int id, String name, Integer positionNo, String rowguid) {
       this.id = id;
       this.name = name;
       this.positionNo = positionNo;
       this.rowguid = rowguid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getPositionNo() {
        return this.positionNo;
    }
    
    public void setPositionNo(Integer positionNo) {
        this.positionNo = positionNo;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }




}


