package beans;
// Generated Jul 27, 2009 9:03:31 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;

/**
 * Iinvoices generated by hbm2java
 */
public class Iinvoices  implements java.io.Serializable {


     private int id;
     private String serie;
     private String number;
     private Integer customerId;
     private Date printDate;
     private String billingName;
     private String billingNo;
     private String billingAddress;
     private BigDecimal total;
     private BigDecimal exchangeRate;
     private String currency;
     private String statusCode;
     private BigDecimal totalDollars;
     private Date creationDate;
     private String comment;
     private String username;
     private Integer customerServiceId;
     private Date voidTime;
     private String voidUsername;
     private String rowguid;

     private ArrayList<IinvoiceDetails> detail = new ArrayList<IinvoiceDetails>();

    public Iinvoices() {
    }

	
    public Iinvoices(int id, String serie, String number, Date printDate, String rowguid) {
        this.id = id;
        this.serie = serie;
        this.number = number;
        this.printDate = printDate;
        this.rowguid = rowguid;
    }
    public Iinvoices(int id, String serie, String number, Integer customerId, Date printDate, String billingName, String billingNo, String billingAddress, BigDecimal total, BigDecimal exchangeRate, String currency, String statusCode, BigDecimal totalDollars, Date creationDate, String comment, String username, Integer customerServiceId, Date voidTime, String voidUsername, String rowguid) {
       this.id = id;
       this.serie = serie;
       this.number = number;
       this.customerId = customerId;
       this.printDate = printDate;
       this.billingName = billingName;
       this.billingNo = billingNo;
       this.billingAddress = billingAddress;
       this.total = total;
       this.exchangeRate = exchangeRate;
       this.currency = currency;
       this.statusCode = statusCode;
       this.totalDollars = totalDollars;
       this.creationDate = creationDate;
       this.comment = comment;
       this.username = username;
       this.customerServiceId = customerServiceId;
       this.voidTime = voidTime;
       this.voidUsername = voidUsername;
       this.rowguid = rowguid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    public Date getPrintDate() {
        return this.printDate;
    }
    
    public void setPrintDate(Date printDate) {
        this.printDate = printDate;
    }
    public String getBillingName() {
        return this.billingName;
    }
    
    public void setBillingName(String billingName) {
        this.billingName = billingName;
    }
    public String getBillingNo() {
        return this.billingNo;
    }
    
    public void setBillingNo(String billingNo) {
        this.billingNo = billingNo;
    }
    public String getBillingAddress() {
        return this.billingAddress;
    }
    
    public void setBillingAddress(String billingAddress) {
        this.billingAddress = billingAddress;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public BigDecimal getExchangeRate() {
        return this.exchangeRate;
    }
    
    public void setExchangeRate(BigDecimal exchangeRate) {
        this.exchangeRate = exchangeRate;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    public String getStatusCode() {
        return this.statusCode;
    }
    
    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode;
    }
    public BigDecimal getTotalDollars() {
        return this.totalDollars;
    }
    
    public void setTotalDollars(BigDecimal totalDollars) {
        this.totalDollars = totalDollars;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Integer getCustomerServiceId() {
        return this.customerServiceId;
    }
    
    public void setCustomerServiceId(Integer customerServiceId) {
        this.customerServiceId = customerServiceId;
    }
    public Date getVoidTime() {
        return this.voidTime;
    }
    
    public void setVoidTime(Date voidTime) {
        this.voidTime = voidTime;
    }
    public String getVoidUsername() {
        return this.voidUsername;
    }
    
    public void setVoidUsername(String voidUsername) {
        this.voidUsername = voidUsername;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }

    public ArrayList<IinvoiceDetails> getDetail() {
        return detail;
    }

    public void setDetail(ArrayList<IinvoiceDetails> detail) {
        this.detail = detail;
    }
}


