package beans;
// Generated Jul 17, 2009 9:34:15 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * CustomerChargesByCft generated by hbm2java
 */
public class CustomerChargesByCft  implements java.io.Serializable {


     private int id;
     private int chargesByCftId;
     private BigDecimal flatFee;
     private String rowguid;

    public CustomerChargesByCft() {
    }

	
    public CustomerChargesByCft(int id, int chargesByCftId, String rowguid) {
        this.id = id;
        this.chargesByCftId = chargesByCftId;
        this.rowguid = rowguid;
    }
    public CustomerChargesByCft(int id, int chargesByCftId, BigDecimal flatFee, String rowguid) {
       this.id = id;
       this.chargesByCftId = chargesByCftId;
       this.flatFee = flatFee;
       this.rowguid = rowguid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getChargesByCftId() {
        return this.chargesByCftId;
    }
    
    public void setChargesByCftId(int chargesByCftId) {
        this.chargesByCftId = chargesByCftId;
    }
    public BigDecimal getFlatFee() {
        return this.flatFee;
    }
    
    public void setFlatFee(BigDecimal flatFee) {
        this.flatFee = flatFee;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }




}


